// resources/assets/src/views/auth/Forgot.vue
<template>
  <form @submit.prevent="submit">
    <div class="input-group mb-3">
      <input
        v-model="email"
        type="email"
        class="form-control"
        :placeholder="$t('auth.email')"
        required
      >
      <div class="input-group-append">
        <div class="input-group-text">
          <span class="fas fa-envelope" />
        </div>
      </div>
    </div>

    <captcha ref="captcha" />

    <div class="alert alert-success" :class="{ 'd-none': !successMsg }">
      <i class="icon fas fa-check" />
      {{ successMsg }}
    </div>
    <div class="alert alert-warning" :class="{ 'd-none': !warningMsg }">
      <i class="icon fas fa-exclamation-triangle" />
      {{ warningMsg }}
    </div>

    <div class="d-flex justify-content-between">
      <a v-t="'auth.forgot.login-link'" :href="`${baseUrl}/auth/login`" class="text-center" />
      <button
        class="btn btn-primary"
        type="submit"
        :disabled="pending"
      >
        <template v-if="pending">
          <i class="fa fa-spinner fa-spin" /> {{ $t('auth.sending') }}
        </template>
        <span v-else>{{ $t('auth.forgot.button') }}</span>
      </button>
    </div>
  </form>
</template>

<script>
import Captcha from '../../components/Captcha.vue'
import emitMounted from '../../components/mixins/emitMounted'

export default {
  name: 'Forgot',
  components: {
    Captcha,
  },
  mixins: [
    emitMounted,
  ],
  props: {
    baseUrl: {
      type: String,
      default: blessing.base_url,
    },
  },
  data: () => ({
    email: '',
    successMsg: '',
    warningMsg: '',
    pending: false,
  }),
  methods: {
    async submit() {
      const { email } = this

      this.pending = true
      const { code, message } = await this.$http.post(
        '/auth/forgot',
        { email, captcha: await this.$refs.captcha.execute() }
      )
      if (code === 0) {
        this.warningMsg = ''
        this.successMsg = message
        this.pending = false
      } else {
        this.warningMsg = message
        this.pending = false
        this.$refs.captcha.refresh()
      }
    },
  },
}
</script>

// resources/assets/src/views/auth/Forgot.tsx
import React, { useState, useRef } from 'react'
import { hot } from 'react-hot-loader/root'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import Alert from '@/components/Alert'
import Captcha from '@/components/Captcha'

const Forgot: React.FC = () => {
  const [email, setEmail] = useState('')
  const [isSending, setIsSending] = useState(false)
  const [successMessage, setSuccessMessage] = useState('')
  const [warningMessage, setWarningMessage] = useState('')
  const ref = useRef<Captcha | null>(null)

  const handleEmailChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(event.target.value)
  }

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setWarningMessage('')
    setIsSending(true)

    const captcha = await ref.current!.execute()
    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/auth/forgot',
      { email, captcha },
    )
    if (code === 0) {
      setSuccessMessage(message)
    } else {
      setWarningMessage(message)
      ref.current!.reset()
    }
    setIsSending(false)
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="input-group mb-3">
        <input
          type="email"
          className="form-control"
          placeholder={t('auth.email')}
          required
          value={email}
          onChange={handleEmailChange}
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-envelope"></i>
          </div>
        </div>
      </div>

      <Captcha ref={ref} />

      <Alert type="success">{successMessage}</Alert>
      <Alert type="warning">{warningMessage}</Alert>

      <div className="d-flex justify-content-between align-items-center">
        <a href={`${blessing.base_url}/auth/login`}>
          {t('auth.forgot.login-link')}
        </a>
        <button className="btn btn-primary" type="submit" disabled={isSending}>
          {isSending ? (
            <>
              <i className="fas fa-spinner fa-spin mr-1" />
              {t('auth.sending')}
            </>
          ) : (
            t('auth.forgot.button')
          )}
        </button>
      </div>
    </form>
  )
}

export default hot(Forgot)
