// resources/assets/src/views/auth/Login.tsx
import React, { useState, useRef, useEffect } from 'react'
import { hot } from 'react-hot-loader/root'
import useBlessingExtra from '@/scripts/hooks/useBlessingExtra'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { showModal } from '@/scripts/notify'
import Alert from '@/components/Alert'
import Captcha from '@/components/Captcha'

type SuccessfulResponse = {
  code: 0
  message: string
  data: { redirectTo: string }
}
type FailedResponse = {
  code: number
  message: string
  data: { login_fails: number }
}
type Response = SuccessfulResponse | FailedResponse

function isSuccessfulResponse(
  response: Response,
): response is SuccessfulResponse {
  return response.code === 0
}

const Login: React.FC = () => {
  const [identification, setIdentification] = useState('')
  const [password, setPassword] = useState('')
  const [remember, setRemember] = useState(false)
  const [hasTooManyFails, setHasTooManyFails] = useState(false)
  const [isPending, setIsPending] = useState(false)
  const [warningMessage, setWarningMessage] = useState('')
  const ref = useRef<Captcha | null>(null)
  const recaptcha = useBlessingExtra<string>('recaptcha')
  const invisibleRecaptcha = useBlessingExtra<boolean>('invisible')

  useEffect(() => {
    setHasTooManyFails(blessing.extra.tooManyFails as boolean)
  }, [])

  const handleIdentificationChange = (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    setIdentification(event.target.value)
  }

  const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPassword(event.target.value)
  }

  const handleRememberChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setRemember(event.target.checked)
  }

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setIsPending(true)

    const response = await fetch.post<Response>('/auth/login', {
      identification,
      password,
      keep: remember,
      captcha: hasTooManyFails ? await ref.current!.execute() : undefined,
    })

    if (isSuccessfulResponse(response)) {
      window.location.href = response.data.redirectTo
    } else {
      setWarningMessage(response.message)
      setIsPending(false)
      ref.current?.reset()

      // only notify user if he/she fails too much at the first time
      if (response.data.login_fails > 3 && !hasTooManyFails) {
        setHasTooManyFails(true)
        if (recaptcha) {
          // no need to notify if using invisible recaptcha
          if (!invisibleRecaptcha) {
            showModal({
              mode: 'alert',
              text: t('auth.tooManyFails.recaptcha'),
            })
          }
        } else {
          showModal({
            mode: 'alert',
            text: t('auth.tooManyFails.captcha'),
          })
        }
      }
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="input-group mb-3">
        <input
          type="text"
          className="form-control"
          placeholder={t('auth.identification')}
          value={identification}
          onChange={handleIdentificationChange}
          required
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-envelope"></i>
          </div>
        </div>
      </div>
      <div className="input-group mb-3">
        <input
          type="password"
          className="form-control"
          placeholder={t('auth.password')}
          value={password}
          onChange={handlePasswordChange}
          required
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-lock"></i>
          </div>
        </div>
      </div>

      {hasTooManyFails && <Captcha ref={ref} />}

      <Alert type="warning">{warningMessage}</Alert>

      <div className="d-flex justify-content-between mb-3">
        <label>
          <input
            type="checkbox"
            className="mr-1"
            checked={remember}
            onChange={handleRememberChange}
          />
          {t('auth.keep')}
        </label>
        <a href={`${blessing.base_url}/auth/forgot`}>{t('auth.forgot-link')}</a>
      </div>

      <button
        className="btn btn-primary btn-block"
        type="submit"
        disabled={isPending}
      >
        {isPending ? (
          <>
            <i className="fas fa-spinner fa-spin mr-1"></i>
            {t('auth.loggingIn')}
          </>
        ) : (
          t('auth.login')
        )}
      </button>
    </form>
  )
}

export default hot(Login)

// resources/assets/src/views/auth/Login.vue
<template>
  <form @submit.prevent="login">
    <div class="input-group mb-3">
      <input
        v-model="identification"
        class="form-control"
        :placeholder="$t('auth.identification')"
        required
      >
      <div class="input-group-append">
        <div class="input-group-text">
          <span class="fas fa-envelope" />
        </div>
      </div>
    </div>
    <div class="input-group mb-3">
      <input
        v-model="password"
        type="password"
        class="form-control"
        :placeholder="$t('auth.password')"
        required
      >
      <div class="input-group-append">
        <div class="input-group-text">
          <span class="fas fa-lock" />
        </div>
      </div>
    </div>

    <captcha v-if="tooManyFails" ref="captcha" />

    <div class="alert alert-warning" :class="{ 'd-none': !warningMsg }">
      <i class="icon fas fa-exclamation-triangle" />
      {{ warningMsg }}
    </div>

    <div class="d-flex justify-content-between mb-3">
      <div>
        <el-switch v-model="remember" :active-text="$t('auth.keep')" />
      </div>
      <a v-t="'auth.forgot-link'" :href="`${baseUrl}/auth/forgot`" />
    </div>

    <button
      class="btn btn-block btn-primary"
      type="submit"
      :disabled="pending"
    >
      <template v-if="pending">
        <i class="fa fa-spinner fa-spin" /> {{ $t('auth.loggingIn') }}
      </template>
      <span v-else>{{ $t('auth.login') }}</span>
    </button>
  </form>
</template>

<script>
import Vue from 'vue'
import { Switch } from 'element-ui'
import Captcha from '../../components/Captcha.vue'
import emitMounted from '../../components/mixins/emitMounted'

Vue.use(Switch)

export default {
  name: 'Login',
  components: {
    Captcha,
  },
  mixins: [
    emitMounted,
  ],
  props: {
    baseUrl: {
      type: String,
      default: blessing.base_url,
    },
  },
  data() {
    return {
      identification: '',
      password: '',
      remember: false,
      tooManyFails: blessing.extra.tooManyFails,
      recaptcha: blessing.extra.recaptcha,
      invisible: blessing.extra.invisible,
      warningMsg: '',
      pending: false,
    }
  },
  methods: {
    async login() {
      const {
        identification, password, remember,
      } = this

      this.pending = true
      const {
        code, message, data: { login_fails: loginFails, redirectTo } = { login_fails: 0 },
      } = await this.$http.post(
        '/auth/login',
        {
          identification,
          password,
          keep: remember,
          captcha: this.tooManyFails
            ? await this.$refs.captcha.execute()
            : void 0,
        }
      )
      if (code === 0) {
        this.$message.success(message)
        setTimeout(() => (window.location = redirectTo), 1000)
      } else {
        if (loginFails > 3 && !this.tooManyFails) {
          if (this.recaptcha) {
            if (!this.invisible) {
              this.$alert(this.$t('auth.tooManyFails.recaptcha'), { type: 'error' })
            }
          } else {
            this.$alert(this.$t('auth.tooManyFails.captcha'), { type: 'error' })
          }
          this.tooManyFails = true
        }
        this.warningMsg = message
        this.pending = false
        this.$refs.captcha.refresh()
      }
    },
  },
}
</script>
