// resources/assets/src/views/auth/Reset.tsx
import React, { useState } from 'react'
import { hot } from 'react-hot-loader/root'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { toast } from '@/scripts/notify'
import Alert from '@/components/Alert'

const Reset: React.FC = () => {
  const [password, setPassword] = useState('')
  const [confirmation, setConfirmation] = useState('')
  const [warningMessage, setWarningMessage] = useState('')
  const [isPending, setIsPending] = useState(false)

  const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPassword(event.target.value)
  }

  const handleConfirmationChange = (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    setConfirmation(event.target.value)
  }

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    if (password !== confirmation) {
      setWarningMessage(t('auth.invalidConfirmPwd'))
      return
    }

    setIsPending(true)
    const { code, message } = await fetch.post<fetch.ResponseBody>(
      location.href.replace(blessing.base_url, ''),
      { password },
    )
    if (code === 0) {
      toast.success(message)
      setTimeout(() => {
        window.location.href = `${blessing.base_url}/auth/login`
      }, 2000)
    } else {
      setWarningMessage(message)
      setIsPending(false)
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="input-group mb-3">
        <input
          type="password"
          required
          minLength={8}
          maxLength={32}
          className="form-control"
          placeholder={t('auth.password')}
          value={password}
          onChange={handlePasswordChange}
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-lock"></i>
          </div>
        </div>
      </div>
      <div className="input-group mb-3">
        <input
          type="password"
          required
          minLength={8}
          maxLength={32}
          className="form-control"
          placeholder={t('auth.repeat-pwd')}
          value={confirmation}
          onChange={handleConfirmationChange}
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-sign-in-alt"></i>
          </div>
        </div>
      </div>

      <Alert type="warning">{warningMessage}</Alert>

      <button
        className="btn btn-primary float-right"
        type="submit"
        disabled={isPending}
      >
        {isPending ? (
          <>
            <i className="fas fa-spinner fa-spin mr-1"></i>
            {t('auth.resetting')}
          </>
        ) : (
          t('auth.reset-button')
        )}
      </button>
    </form>
  )
}

export default hot(Reset)

// resources/assets/src/views/auth/Reset.vue
<template>
  <form @submit.prevent="reset">
    <div class="input-group mb-3">
      <input
        v-model="password"
        type="password"
        class="form-control"
        :placeholder="$t('auth.password')"
        required
        minlength="8"
        maxlength="32"
      >
      <div class="input-group-append">
        <div class="input-group-text">
          <span class="fas fa-lock" />
        </div>
      </div>
    </div>
    <div class="input-group mb-3">
      <input
        ref="confirm"
        v-model="confirm"
        type="password"
        class="form-control"
        :placeholder="$t('auth.repeat-pwd')"
        required
        minlength="8"
        maxlength="32"
      >
      <div class="input-group-append">
        <div class="input-group-text">
          <span class="fas fa-sign-in-alt" />
        </div>
      </div>
    </div>

    <div class="alert alert-info" :class="{ 'd-none': !infoMsg }">
      <i class="icon fas fa-info" />
      {{ infoMsg }}
    </div>
    <div class="alert alert-warning" :class="{ 'd-none': !warningMsg }">
      <i class="icon fas fa-exclamation-triangle" />
      {{ warningMsg }}
    </div>

    <button
      class="btn btn-primary float-right"
      type="submit"
      :disabled="pending"
    >
      <template v-if="pending">
        <i class="fa fa-spinner fa-spin" /> {{ $t('auth.resetting') }}
      </template>
      <span v-else>{{ $t('auth.reset-button') }}</span>
    </button>
  </form>
</template>

<script>
import emitMounted from '../../components/mixins/emitMounted'

export default {
  name: 'Reset',
  mixins: [
    emitMounted,
  ],
  data() {
    return {
      uid: +this.$route[1],
      password: '',
      confirm: '',
      infoMsg: '',
      warningMsg: '',
      pending: false,
    }
  },
  methods: {
    async reset() {
      const { password, confirm } = this

      if (password !== confirm) {
        this.infoMsg = this.$t('auth.invalidConfirmPwd')
        this.$refs.confirm.focus()
        return
      }

      this.pending = true
      const { code, message } = await this.$http.post(
        `/auth/reset/${this.uid}${location.search}`,
        { password },
      )
      if (code === 0) {
        this.$message.success(message)
        window.location = `${blessing.base_url}/auth/login`
      } else {
        this.infoMsg = ''
        this.warningMsg = message
        this.pending = false
      }
    },
  },
}
</script>
