// resources/assets/src/views/auth/Login.tsx
import React, { useState, useRef, useEffect } from 'react'
import { hot } from 'react-hot-loader/root'
import useBlessingExtra from '@/scripts/hooks/useBlessingExtra'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { showModal } from '@/scripts/notify'
import Alert from '@/components/Alert'
import Captcha from '@/components/Captcha'

type SuccessfulResponse = {
  code: 0
  message: string
  data: { redirectTo: string }
}
type FailedResponse = {
  code: number
  message: string
  data: { login_fails: number }
}
type Response = SuccessfulResponse | FailedResponse

function isSuccessfulResponse(
  response: Response,
): response is SuccessfulResponse {
  return response.code === 0
}

const Login: React.FC = () => {
  const [identification, setIdentification] = useState('')
  const [password, setPassword] = useState('')
  const [remember, setRemember] = useState(false)
  const [hasTooManyFails, setHasTooManyFails] = useState(false)
  const [isPending, setIsPending] = useState(false)
  const [warningMessage, setWarningMessage] = useState('')
  const ref = useRef<Captcha | null>(null)
  const recaptcha = useBlessingExtra<string>('recaptcha')
  const invisibleRecaptcha = useBlessingExtra<boolean>('invisible')

  useEffect(() => {
    setHasTooManyFails(blessing.extra.tooManyFails as boolean)
  }, [])

  const handleIdentificationChange = (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    setIdentification(event.target.value)
  }

  const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPassword(event.target.value)
  }

  const handleRememberChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setRemember(event.target.checked)
  }

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setIsPending(true)

    const response = await fetch.post<Response>('/auth/login', {
      identification,
      password,
      keep: remember,
      captcha: hasTooManyFails ? await ref.current!.execute() : undefined,
    })

    if (isSuccessfulResponse(response)) {
      window.location.href = response.data.redirectTo
    } else {
      setWarningMessage(response.message)
      setIsPending(false)
      ref.current?.reset()

      // only notify user if he/she fails too much at the first time
      if (response.data.login_fails > 3 && !hasTooManyFails) {
        setHasTooManyFails(true)
        if (recaptcha) {
          // no need to notify if using invisible recaptcha
          if (!invisibleRecaptcha) {
            showModal({
              mode: 'alert',
              text: t('auth.tooManyFails.recaptcha'),
            })
          }
        } else {
          showModal({
            mode: 'alert',
            text: t('auth.tooManyFails.captcha'),
          })
        }
      }
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="input-group mb-3">
        <input
          type="text"
          className="form-control"
          placeholder={t('auth.identification')}
          value={identification}
          onChange={handleIdentificationChange}
          required
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-envelope"></i>
          </div>
        </div>
      </div>
      <div className="input-group mb-3">
        <input
          type="password"
          className="form-control"
          placeholder={t('auth.password')}
          value={password}
          onChange={handlePasswordChange}
          required
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-lock"></i>
          </div>
        </div>
      </div>

      {hasTooManyFails && <Captcha ref={ref} />}

      <Alert type="warning">{warningMessage}</Alert>

      <div className="d-flex justify-content-between mb-3">
        <label>
          <input
            type="checkbox"
            className="mr-1"
            checked={remember}
            onChange={handleRememberChange}
          />
          {t('auth.keep')}
        </label>
        <a href={`${blessing.base_url}/auth/forgot`}>{t('auth.forgot-link')}</a>
      </div>

      <button
        className="btn btn-primary btn-block"
        type="submit"
        disabled={isPending}
      >
        {isPending ? (
          <>
            <i className="fas fa-spinner fa-spin mr-1"></i>
            {t('auth.loggingIn')}
          </>
        ) : (
          t('auth.login')
        )}
      </button>
    </form>
  )
}

export default hot(Login)

// resources/assets/src/components/auth/Login.vue
<template>
    <form>
        <div class="form-group has-feedback">
            <input
                type="email"
                v-model="identification"
                class="form-control"
                :placeholder="$t('auth.identification')"
                ref="identification"
            >
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
            <input
                type="password"
                v-model="password"
                class="form-control"
                :placeholder="$t('auth.password')"
                ref="password"
            >
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>

        <div v-if="tooManyFails" class="row">
            <div class="col-xs-8">
                <div class="form-group has-feedback">
                    <input
                        type="text"
                        v-model="captcha"
                        class="form-control"
                        :placeholder="$t('auth.captcha')"
                        ref="captcha"
                    >
                </div>
            </div>
            <div class="col-xs-4">
                <img
                    class="pull-right captcha"
                    :src="`${baseUrl}/auth/captcha?v=${time}`"
                    alt="CAPTCHA"
                    :title="$t('auth.change-captcha')"
                    @click="refreshCaptcha"
                    data-placement="top"
                    data-toggle="tooltip"
                >
            </div>
        </div>

        <div class="callout callout-info" :class="{ hide: !infoMsg }">{{ infoMsg }}</div>
        <div class="callout callout-warning" :class="{ hide: !warningMsg }">{{ warningMsg }}</div>

        <div class="row">
            <div class="col-xs-6">
                <div class="checkbox icheck" style="margin-top: 0;">
                    <label>
                        <input v-model="remember" type="checkbox"> {{ $t('auth.keep') }}
                    </label>
                </div>
            </div>
            <div class="col-xs-6">
                <a class="pull-right" :href="`${baseUrl}/auth/forgot`" v-t="'auth.forgot-link'"></a>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <button v-if="pending" disabled class="btn btn-primary btn-block btn-flat">
                    <i class="fa fa-spinner fa-spin"></i> {{ $t('auth.loggingIn') }}
                </button>
                <button
                    v-else
                    @click.prevent="login"
                    class="btn btn-primary btn-block btn-flat"
                >{{ $t('auth.login') }}</button>
            </div>
        </div>
    </form>
</template>

<script>
import { swal } from '../../js/notify';

export default {
    name: 'Login',
    props: {
        baseUrl: {
            default: blessing.base_url
        }
    },
    data() {
        return {
            identification: '',
            password: '',
            captcha: '',
            remember: false,
            time: Date.now(),
            tooManyFails: blessing.extra.tooManyFails,
            infoMsg: '',
            warningMsg: '',
            pending: false,
        };
    },
    methods: {
        async login() {
            const {
                identification, password, captcha, remember
            } = this;

            if (!identification) {
                this.infoMsg = this.$t('auth.emptyIdentification');
                this.$refs.identification.focus();
                return;
            }

            if (!password) {
                this.infoMsg = this.$t('auth.emptyPassword');
                this.$refs.password.focus();
                return;
            }

            if (this.tooManyFails && !captcha) {
                this.infoMsg = this.$t('auth.emptyCaptcha');
                this.$refs.captcha.focus();
                return;
            }

            this.pending = true;
            const { errno, msg, login_fails } = await this.$http.post(
                '/auth/login',
                {
                    identification,
                    password,
                    keep: remember,
                    captcha: this.tooManyFails ? captcha : undefined
                }
            );
            if (errno === 0) {
                swal({ type: 'success', text: msg });
                setTimeout(() => {
                    window.location = `${blessing.base_url}/${blessing.redirect_to || 'user'}`;
                }, 1000);
            } else {
                if (login_fails > 3 && !this.tooManyFails) {
                    swal({ type: 'error', text: this.$t('auth.tooManyFails') });
                    this.tooManyFails = true;
                }
                this.refreshCaptcha();
                this.infoMsg = '';
                this.warningMsg = msg;
                this.pending = false;
            }
        },
        refreshCaptcha() {
            this.time = Date.now();
        }
    }
};
</script>

<style lang="stylus">
#login-button {
    margin-top: 5px;
}
</style>
