// resources/assets/src/views/auth/Reset.tsx
import React, { useState } from 'react'
import { hot } from 'react-hot-loader/root'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { toast } from '@/scripts/notify'
import Alert from '@/components/Alert'

const Reset: React.FC = () => {
  const [password, setPassword] = useState('')
  const [confirmation, setConfirmation] = useState('')
  const [warningMessage, setWarningMessage] = useState('')
  const [isPending, setIsPending] = useState(false)

  const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPassword(event.target.value)
  }

  const handleConfirmationChange = (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    setConfirmation(event.target.value)
  }

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    if (password !== confirmation) {
      setWarningMessage(t('auth.invalidConfirmPwd'))
      return
    }

    setIsPending(true)
    const { code, message } = await fetch.post<fetch.ResponseBody>(
      location.href.replace(blessing.base_url, ''),
      { password },
    )
    if (code === 0) {
      toast.success(message)
      setTimeout(() => {
        window.location.href = `${blessing.base_url}/auth/login`
      }, 2000)
    } else {
      setWarningMessage(message)
      setIsPending(false)
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="input-group mb-3">
        <input
          type="password"
          required
          minLength={8}
          maxLength={32}
          className="form-control"
          placeholder={t('auth.password')}
          value={password}
          onChange={handlePasswordChange}
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-lock"></i>
          </div>
        </div>
      </div>
      <div className="input-group mb-3">
        <input
          type="password"
          required
          minLength={8}
          maxLength={32}
          className="form-control"
          placeholder={t('auth.repeat-pwd')}
          value={confirmation}
          onChange={handleConfirmationChange}
        />
        <div className="input-group-append">
          <div className="input-group-text">
            <i className="fas fa-sign-in-alt"></i>
          </div>
        </div>
      </div>

      <Alert type="warning">{warningMessage}</Alert>

      <button
        className="btn btn-primary float-right"
        type="submit"
        disabled={isPending}
      >
        {isPending ? (
          <>
            <i className="fas fa-spinner fa-spin mr-1"></i>
            {t('auth.resetting')}
          </>
        ) : (
          t('auth.reset-button')
        )}
      </button>
    </form>
  )
}

export default hot(Reset)

// resources/assets/src/components/auth/Reset.vue
<template>
    <form>
        <div class="form-group has-feedback">
            <input
                v-model="password"
                type="password"
                class="form-control"
                ref="password"
                :placeholder="$t('auth.password')"
            >
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
            <input
                v-model="confirm"
                type="password"
                class="form-control"
                ref="confirm"
                :placeholder="$t('auth.repeat-pwd')"
            >
            <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
        </div>

        <div class="callout callout-info" :class="{ hide: !infoMsg }">{{ infoMsg }}</div>
        <div class="callout callout-warning" :class="{ hide: !warningMsg }">{{ warningMsg }}</div>

        <div class="row">
            <div class="col-xs-8">
            </div>
            <div class="col-xs-4">
                <button v-if="pending" disabled class="btn btn-primary btn-block btn-flat">
                    <i class="fa fa-spinner fa-spin"></i> {{ $t('auth.resetting') }}
                </button>
                <button v-else @click.prevent="reset" class="btn btn-primary btn-block btn-flat">
                    {{ $t('auth.reset-button') }}
                </button>
            </div>
        </div>
    </form>
</template>

<script>
import { swal } from '../../js/notify';

export default {
    name: 'Reset',
    data() {
        return {
            uid: +this.$route[1],
            password: '',
            confirm: '',
            infoMsg: '',
            warningMsg: '',
            pending: false,
        };
    },
    methods: {
        async reset() {
            const { password, confirm } = this;

            if (!password) {
                this.infoMsg = this.$t('auth.emptyPassword');
                this.$refs.password.focus();
                return;
            }

            if (password.length < 8 || password.length > 32) {
                this.infoMsg = this.$t('auth.invalidPassword');
                this.$refs.password.focus();
                return;
            }

            if (password !== confirm) {
                this.infoMsg = this.$t('auth.invalidConfirmPwd');
                this.$refs.confirm.focus();
                return;
            }

            this.pending = true;
            const { errno, msg } = await this.$http.post(
                `/auth/reset/${this.uid}${location.search}`,
                { password }
            );
            if (errno === 0) {
                await swal({ type: 'success', text: msg });
                window.location = `${blessing.base_url}/auth/login`;
            } else {
                this.infoMsg = '';
                this.warningMsg = msg;
                this.pending = false;
            }
        }
    }
};
</script>
