// resources/assets/src/views/user/Dashboard.vue
<template>
  <div>
    <email-verification />
    <div class="card card-primary card-outline">
      <div class="card-header">
        <h3 v-t="'user.used.title'" class="card-title" />
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-1" />
          <div class="col-md-6">
            <div class="info-box bg-teal">
              <span class="info-box-icon">
                <i class="fas fa-gamepad" />
              </span>
              <div class="info-box-content">
                <span class="info-box-text">{{ $t('user.used.players') }}</span>
                <span class="info-box-number">
                  <b>{{ playersUsed }}</b> / {{ playersTotal }}
                </span>
                <div class="progress">
                  <div class="progress-bar" :style="{ width: playersPercentage + '%' }" />
                </div>
              </div>
            </div>
            <div class="info-box bg-maroon">
              <span class="info-box-icon">
                <i class="fas fa-hdd" />
              </span>
              <div class="info-box-content">
                <span class="info-box-text">{{ $t('user.used.storage') }}</span>
                <span class="info-box-number">
                  <template v-if="storageUsed > 1024">
                    <b>{{ ~~(storageUsed / 1024) }}</b> / {{ ~~(storageTotal / 1024) }} MB
                  </template>
                  <template v-else>
                    <b>{{ storageUsed }}</b> / {{ storageTotal }} KB
                  </template>
                </span>
                <div class="progress">
                  <div class="progress-bar" :style="{ width: storagePercentage + '%' }" />
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <p class="text-center score-title">
              <strong v-t="'user.cur-score'" />
            </p>
            <p id="score" data-toggle="modal" data-target="#modal-score-instruction">
              {{ animatedScore }}
            </p>
            <p v-t="'user.score-notice'" class="text-center score-notice" />
          </div>
        </div>
      </div>
      <div class="card-footer">
        <button
          v-if="canSign"
          class="btn bg-gradient-primary pl-5 pr-5"
          :disabled="signing"
          @click="sign"
        >
          <i class="far fa-calendar-check" aria-hidden="true" /> &nbsp;{{ $t('user.sign') }}
        </button>
        <button
          v-else
          class="btn bg-gradient-primary pl-4 pr-4"
          :title="$t('user.last-sign', { time: lastSignAt.toLocaleString() })"
          disabled
        >
          <i class="far fa-calendar-check" aria-hidden="true" /> &nbsp;
          {{ remainingTimeText }}
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import Tween from '@tweenjs/tween.js'
import EmailVerification from '../../components/EmailVerification.vue'
import emitMounted from '../../components/mixins/emitMounted'

const ONE_DAY = 24 * 3600 * 1000

export default {
  name: 'Dashboard',
  components: {
    EmailVerification,
  },
  mixins: [
    emitMounted,
  ],
  data: () => ({
    score: 0,
    tweenedScore: 0,
    lastSignAt: new Date(),
    signAfterZero: false,
    signGap: 0,
    signing: false,
    playersUsed: 0,
    playersTotal: 1,
    storageUsed: 0,
    storageTotal: 1,
    tween: null,
  }),
  computed: {
    playersPercentage() {
      return this.playersUsed / this.playersTotal * 100
    },
    storagePercentage() {
      return this.storageUsed / this.storageTotal * 100
    },
    signRemainingTime() {
      if (this.signAfterZero) {
        const today = (new Date()).setHours(0, 0, 0, 0)
        const tomorrow = today + ONE_DAY
        return this.lastSignAt.valueOf() < today ? 0 : tomorrow - Date.now()
      }
      return this.lastSignAt.valueOf() + this.signGap - Date.now()
    },
    remainingTimeText() {
      const time = this.signRemainingTime / 1000 / 60
      if (time < 60) {
        return this.$t(
          'user.sign-remain-time',
          { time: ~~time, unit: this.$t('user.time-unit-min') }
        )
      }
      return this.$t(
        'user.sign-remain-time',
        { time: ~~(time / 60), unit: this.$t('user.time-unit-hour') }
      )
    },
    canSign() {
      return this.signRemainingTime <= 0
    },
    animatedScore() {
      return this.tweenedScore.toFixed(0)
    },
  },
  watch: {
    score(newValue) {
      this.tween.to({ tweenedScore: newValue }, 1000).start()
    },
  },
  created() {
    this.tween = new Tween.Tween(this.$data)
  },
  beforeMount() {
    this.fetchScoreInfo()
  },
  mounted() {
    function animate() {
      requestAnimationFrame(animate)
      Tween.update()
    }
    animate()
  },
  methods: {
    async fetchScoreInfo() {
      const { data } = await this.$http.get('/user/score-info')
      this.lastSignAt = new Date(data.user.lastSignAt)
      this.signAfterZero = data.signAfterZero
      this.signGap = data.signGapTime * 3600 * 1000
      this.playersUsed = data.stats.players.used
      this.playersTotal = data.stats.players.total
      this.storageUsed = data.stats.storage.used
      this.storageTotal = data.stats.storage.total
      this.score = data.user.score
    },
    async sign() {
      this.signing = true
      const {
        code, message, data,
      } = await this.$http.post('/user/sign')

      if (code === 0) {
        this.$message.success(message)
        this.score = data.score
        this.lastSignAt = new Date()
        this.storageUsed = data.storage.used
        this.storageTotal = data.storage.total
      } else {
        this.$message.warning(message)
      }
      this.signing = false
    },
  },
}
</script>

<style lang="stylus">
.score-title
  margin-top 5px

  @media (max-width 768px)
    margin-top 12px

#score
  font-family Minecraft
  font-size 50px
  text-align center
  margin-top 20px
  cursor help

.score-notice
  font-size smaller
  margin-top 20px
</style>

// resources/assets/src/views/user/Dashboard/index.tsx
import React, { useState, useEffect, useCallback } from 'react'
import styled from '@emotion/styled'
import { hot } from 'react-hot-loader/root'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { toast } from '@/scripts/notify'
import useTween from '@/scripts/hooks/useTween'
import urls from '@/scripts/urls'
import * as breakpoints from '@/styles/breakpoints'
import InfoBox from './InfoBox'
import SignButton from './SignButton'

type ScoreInfo = {
  signAfterZero: boolean
  signGapTime: number
  stats: { players: Stat; storage: Stat }
  user: { score: number; lastSignAt: string }
}

type Stat = {
  used: number
  total: number
}

type SignReturn = {
  score: number
  storage: Stat
}

const ScoreTitle = styled.p`
  font-weight: bold;
  margin-top: 5px;
  ${breakpoints.lessThan(breakpoints.Breakpoint.md)} {
    margin-top: 12px;
  }
`
const Score = styled.p`
  font-family: 'Minecraft';
  font-size: 50px;
  margin-top: 20px;
  cursor: help;
`
const ScoreNotice = styled.p`
  font-size: smaller;
  margin-top: 20px;
`

const Dashboard: React.FC = () => {
  const [loading, setLoading] = useState(false)
  const [players, setPlayers] = useState<Stat>({ used: 0, total: 1 })
  const [storage, setStorage] = useState<Stat>({ used: 0, total: 1 })
  const [score, setScore] = useTween(0)
  const [lastSign, setLastSign] = useState(new Date())
  const [canSignAfterZero, setCanSignAfterZero] = useState(false)
  const [signGap, setSignGap] = useState(24)

  useEffect(() => {
    const fetchInfo = async () => {
      setLoading(true)
      const { data } = await fetch.get<fetch.ResponseBody<ScoreInfo>>(
        urls.user.score(),
      )
      setPlayers(data.stats.players)
      setStorage(data.stats.storage)
      setScore(data.user.score)
      setLastSign(new Date(data.user.lastSignAt))
      setCanSignAfterZero(data.signAfterZero)
      setSignGap(data.signGapTime)
      setLoading(false)
    }
    fetchInfo()
  }, [])

  const handleSign = useCallback(async () => {
    setLoading(true)
    const { code, message, data } = await fetch.post<
      fetch.ResponseBody<SignReturn>
    >(urls.user.sign())

    if (code === 0) {
      toast.success(message)
      setLastSign(new Date())
      setScore(data.score)
      setStorage(data.storage)
    } else {
      toast.warning(message)
    }
    setLoading(false)
  }, [])

  return (
    <div className="card card-primary card-outline">
      <div className="card-header">
        <h3 className="card-title">{t('user.used.title')}</h3>
      </div>
      <div className="card-body">
        <div className="row">
          <div className="col-md-1"></div>
          <div className="col-md-6">
            <InfoBox
              color="teal"
              icon="gamepad"
              name={t('user.used.players')}
              used={players.used}
              total={players.total}
              unit=""
            />
            {storage.used > 1024 ? (
              <InfoBox
                color="maroon"
                icon="hdd"
                name={t('user.used.storage')}
                used={~~(storage.used / 1024)}
                total={~~(storage.total / 1024)}
                unit="MB"
              />
            ) : (
              <InfoBox
                color="maroon"
                icon="hdd"
                name={t('user.used.storage')}
                used={storage.used}
                total={storage.total}
                unit="KB"
              />
            )}
          </div>
          <div className="col-md-4 text-center">
            <ScoreTitle>{t('user.cur-score')}</ScoreTitle>
            <Score data-toggle="modal" data-target="#modal-score-instruction">
              {~~score}
            </Score>
            <ScoreNotice>{t('user.score-notice')}</ScoreNotice>
          </div>
        </div>
      </div>
      <div className="card-footer">
        <SignButton
          isLoading={loading}
          lastSign={lastSign}
          canSignAfterZero={canSignAfterZero}
          signGap={signGap}
          onClick={handleSign}
        />
      </div>
    </div>
  )
}

export default hot(Dashboard)
