// resources/assets/src/views/skinlib/Show/index.tsx
import React, { useState, useEffect } from 'react'
import { createPortal } from 'react-dom'
import { hot } from 'react-hot-loader/root'
import useBlessingExtra from '@/scripts/hooks/useBlessingExtra'
import useMount from '@/scripts/hooks/useMount'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { showModal, toast } from '@/scripts/notify'
import { Texture, TextureType } from '@/scripts/types'
import ButtonEdit from '@/components/ButtonEdit'
import ViewerSkeleton from '@/components/ViewerSkeleton'
import ModalApply from '@/views/user/Closet/ModalApply'
import removeClosetItem from '@/views/user/Closet/removeClosetItem'
import setAsAvatar from '@/views/user/Closet/setAsAvatar'
import addClosetItem from './addClosetItem'

export type Badge = {
  color: string
  text: string
}

const Previewer = React.lazy(() => import('@/components/Viewer'))

const Show: React.FC = () => {
  const [texture, setTexture] = useState<Texture>({} as Texture)
  const [showModalApply, setShowModalApply] = useState(false)
  const [liked, setLiked] = useState(false)
  const nickname = useBlessingExtra<string>('nickname')
  const isUploaderExists = useBlessingExtra<boolean>('uploaderExists')
  const currentUid = useBlessingExtra<number>('currentUid', 0)
  const isAdmin = useBlessingExtra<boolean>('admin')
  const badges = useBlessingExtra<Badge[]>('badges', [])
  const canBeDownloaded = useBlessingExtra<boolean>('download')
  const reportScore = useBlessingExtra<number>('report')
  const container = useMount('#previewer')

  useEffect(() => {
    const fetchInfo = async () => {
      const url = location.href
        .replace(blessing.base_url, '')
        .replace('show', 'info')

      const { data } = await fetch.get<fetch.ResponseBody<Texture>>(url)
      setTexture(data)
    }
    fetchInfo()
  }, [])

  useEffect(() => {
    setLiked(blessing.extra.inCloset as boolean)
  }, [])

  const handleEditName = async () => {
    let name: string
    try {
      const { value } = await showModal({
        mode: 'prompt',
        text: t('skinlib.setNewTextureName'),
        input: texture.name,
        validator: (value: string) => {
          if (!value) {
            return t('skinlib.emptyNewTextureName')
          }
        },
      })
      name = value
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/skinlib/rename',
      {
        tid: texture.tid,
        new_name: name,
      },
    )
    if (code === 0) {
      toast.success(message)
      setTexture((texture) => ({ ...texture, name }))
    } else {
      toast.error(message)
    }
  }

  const handleSwitchType = async () => {
    let type: TextureType
    try {
      const { value } = await showModal({
        mode: 'prompt',
        text: t('skinlib.setNewTextureModel'),
        input: texture.type,
        inputType: 'radios',
        choices: [
          { text: 'Steve', value: TextureType.Steve },
          { text: 'Alex', value: TextureType.Alex },
          { text: t('general.cape'), value: TextureType.Cape },
        ],
      })
      type = value as TextureType
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/skinlib/model',
      {
        tid: texture.tid,
        model: type,
      },
    )
    if (code === 0) {
      toast.success(message)
      setTexture((texture) => ({ ...texture, type }))
    } else {
      toast.error(message)
    }
  }

  const handleAddItemClick = async () => {
    const ok = await addClosetItem(texture)
    if (ok) {
      setTexture((texture) => ({ ...texture, likes: texture.likes + 1 }))
      setLiked(true)
    }
  }

  const handleRemoveItemClick = async () => {
    const ok = await removeClosetItem(texture.tid)
    if (ok) {
      setTexture((texture) => ({ ...texture, likes: texture.likes - 1 }))
      setLiked(false)
    }
  }

  const handleSetAsAvatar = () => setAsAvatar(texture.tid)

  const handleDownloadClick = () => {
    const a = document.createElement('a')
    a.href = `${blessing.base_url}/raw/${texture.tid}`
    a.download = `${texture.name}.png`
    a.click()
  }

  const handleReport = async () => {
    const prompt = (() => {
      if (reportScore > 0) {
        return t('skinlib.report.positive', { score: reportScore })
      } else if (reportScore < 0) {
        return t('skinlib.report.negative', { score: -reportScore })
      }
      return ''
    })()

    let reason: string
    try {
      const { value } = await showModal({
        mode: 'prompt',
        title: t('skinlib.report.title'),
        text: prompt,
        placeholder: t('skinlib.report.reason'),
      })
      reason = value
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/skinlib/report',
      {
        tid: texture.tid,
        reason,
      },
    )
    if (code === 0) {
      toast.success(message)
    } else {
      toast.error(message)
    }
  }

  const handlePrivacyClick = async () => {
    try {
      await showModal({
        text: texture.public
          ? t('skinlib.setPrivateNotice')
          : t('skinlib.setPublicNotice'),
      })
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/skinlib/privacy',
      { tid: texture.tid },
    )
    if (code === 0) {
      toast.success(message)
      setTexture((texture) => ({ ...texture, public: !texture.public }))
    } else {
      toast.error(message)
    }
  }

  const handleDeleteTextureClick = async () => {
    try {
      await showModal({
        text: t('skinlib.deleteNotice'),
        okButtonType: 'danger',
      })
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/skinlib/delete',
      { tid: texture.tid },
    )
    if (code === 0) {
      toast.success(message)
      setTimeout(() => {
        window.location.href = `${blessing.base_url}/skinlib`
      }, 2000)
    } else {
      toast.error(message)
    }
  }

  const handleOpenModalApply = () => setShowModalApply(true)
  const handleCloseModalApply = () => setShowModalApply(false)

  const linkToUploader = (() => {
    const search = new URLSearchParams()
    search.append(
      'filter',
      texture.type === TextureType.Cape ? TextureType.Cape : 'skin',
    )
    search.append('uploader', texture.uploader?.toString())

    return `${blessing.base_url}/skinlib?${search}`
  })()

  const canEdit = currentUid === texture.uploader || isAdmin
  const textureUrl = `${blessing.base_url}/textures/${texture.hash}`

  return (
    <React.Fragment>
      {createPortal(
        <React.Suspense fallback={<ViewerSkeleton />}>
          <Previewer
            {...{
              [texture.type === TextureType.Cape
                ? TextureType.Cape
                : 'skin']: textureUrl,
            }}
            isAlex={texture.type === TextureType.Alex}
            initPositionZ={60}
          >
            {currentUid === 0 ? (
              <button
                className="btn btn-outline-secondary"
                title={t('skinlib.show.anonymous')}
                disabled
              >
                {t('skinlib.addToCloset')}
              </button>
            ) : (
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  {liked && (
                    <button
                      className="btn btn-outline-success mr-2"
                      onClick={handleOpenModalApply}
                    >
                      {t('skinlib.apply')}
                    </button>
                  )}
                  {liked ? (
                    <button
                      className="btn btn-outline-primary mr-2"
                      onClick={handleRemoveItemClick}
                    >
                      {t('skinlib.removeFromCloset')}
                    </button>
                  ) : (
                    <button
                      className="btn btn-outline-primary mr-2"
                      onClick={handleAddItemClick}
                    >
                      {t('skinlib.addToCloset')}
                    </button>
                  )}
                  {texture.type !== TextureType.Cape && (
                    <button
                      className="btn btn-outline-info mr-2"
                      onClick={handleSetAsAvatar}
                    >
                      {t('user.setAsAvatar')}
                    </button>
                  )}
                  {canBeDownloaded && (
                    <button
                      className="btn btn-outline-info mr-2"
                      onClick={handleDownloadClick}
                    >
                      {t('skinlib.show.download')}
                    </button>
                  )}
                  <button
                    className="btn btn-outline-info mr-2"
                    onClick={handleReport}
                  >
                    {t('skinlib.report.title')}
                  </button>
                </div>
                <div
                  className={liked ? 'text-red' : 'text-gray'}
                  title={t('skinlib.show.likes')}
                >
                  <i className="fas fa-heart mr-1" />
                  <span>{texture.likes}</span>
                </div>
              </div>
            )}
          </Previewer>
        </React.Suspense>,
        container,
      )}
      <div className="card card-primary">
        <div className="card-header">
          <h3 className="card-title">{t('skinlib.show.detail')}</h3>
        </div>
        <div className="card-body">
          <div className="container">
            <div className="row mt-2 mb-4">
              <div className="col-4">{t('skinlib.show.name')}</div>
              <div className="col-7 text-truncate" title={texture.name}>
                {texture.name}
              </div>
              {canEdit && (
                <div className="col-1">
                  <ButtonEdit
                    title={t('skinlib.show.edit')}
                    onClick={handleEditName}
                  />
                </div>
              )}
            </div>
            <div className="row my-4">
              <div className="col-4">{t('skinlib.show.model')}</div>
              <div className="col-7">
                {texture.type === TextureType.Cape
                  ? t('general.cape')
                  : texture.type}
              </div>
              {canEdit && (
                <div className="col-1">
                  <ButtonEdit
                    title={t('skinlib.show.edit')}
                    onClick={handleSwitchType}
                  />
                </div>
              )}
            </div>
            <div className="row my-4">
              <div className="col-4">Hash</div>
              <div className="col-8 text-truncate" title={texture.hash}>
                {texture.hash}
              </div>
            </div>
            <div className="row my-4">
              <div className="col-4">{t('skinlib.show.size')}</div>
              <div className="col-8">{texture.size} KB</div>
            </div>
            <div className="row my-4">
              <div className="col-4">{t('skinlib.show.uploader')}</div>
              <div className="col-8 text-truncate">
                {isUploaderExists ? (
                  <React.Fragment>
                    <div>
                      <a href={linkToUploader} target="_blank">
                        {nickname}
                      </a>
                    </div>
                    <div>
                      {badges.map((badge) => (
                        <span
                          className={`badge bg-${badge.color} mr-2`}
                          key={badge.text}
                        >
                          {badge.text}
                        </span>
                      ))}
                    </div>
                  </React.Fragment>
                ) : (
                  nickname
                )}
              </div>
            </div>
            <div className="row mt-4 mb-2">
              <div className="col-4">{t('skinlib.show.upload-at')}</div>
              <div className="col-8">{texture.upload_at}</div>
            </div>
          </div>
        </div>
      </div>
      {canEdit && (
        <div className="card card-warning">
          <div className="card-header">
            <h3 className="card-title">{t('admin.operationsTitle')}</h3>
          </div>
          <div className="card-body">
            <p>{t('skinlib.show.manage-notice')}</p>
          </div>
          <div className="card-footer">
            <div className="container d-flex justify-content-between">
              <button className="btn btn-warning" onClick={handlePrivacyClick}>
                {texture.public
                  ? t('skinlib.setAsPrivate')
                  : t('skinlib.setAsPublic')}
              </button>
              <button
                className="btn btn-danger"
                onClick={handleDeleteTextureClick}
              >
                {t('skinlib.show.delete-texture')}
              </button>
            </div>
          </div>
        </div>
      )}
      <ModalApply
        show={showModalApply}
        canAdd={false}
        {...{
          [texture.type === TextureType.Cape
            ? TextureType.Cape
            : 'skin']: texture.tid,
        }}
        onClose={handleCloseModalApply}
      />
    </React.Fragment>
  )
}

export default hot(Show)

// resources/assets/src/views/skinlib/Show.vue
<template>
  <div class="row">
    <div class="col-md-8">
      <previewer
        :skin="type !== 'cape' && textureUrl"
        :cape="type === 'cape' ? textureUrl : ''"
        :model="type"
        :init-position-z="60"
      >
        <template #footer>
          <button
            v-if="anonymous"
            class="btn btn-outline-secondary"
            disabled
            :title="$t('skinlib.show.anonymous')"
          >
            {{ $t('skinlib.addToCloset') }}
          </button>
          <div v-else class="d-flex justify-content-between">
            <div>
              <button
                v-if="liked"
                class="btn btn-outline-success mr-2"
                data-toggle="modal"
                data-target="#modal-use-as"
                @click="fetchPlayersList"
              >
                {{ $t('skinlib.apply') }}
              </button>
              <button
                v-if="liked"
                class="btn btn-outline-primary mr-2"
                data-test="removeFromCloset"
                @click="removeFromCloset"
              >
                {{ $t('skinlib.removeFromCloset') }}
              </button>
              <button
                v-else
                class="btn btn-outline-primary mr-2"
                data-test="addToCloset"
                @click="addToCloset"
              >
                {{ $t('skinlib.addToCloset') }}
              </button>
              <button
                v-if="type !== 'cape'"
                class="btn btn-outline-info mr-2"
                data-test="setAsAvatar"
                @click="setAsAvatar"
              >
                {{ $t('user.setAsAvatar') }}
              </button>
              <button
                v-if="canBeDownloaded"
                class="btn btn-outline-info mr-2"
                data-test="download"
                @click="download"
              >
                {{ $t('skinlib.show.download') }}
              </button>
              <button
                class="btn btn-outline-info mr-2"
                data-test="report"
                @click="report"
              >
                {{ $t('skinlib.report.title') }}
              </button>
            </div>
            <div
              class="pt-2 likes"
              :class="[liked ? 'text-red' : 'text-gray']"
              :title="$t('skinlib.show.likes')"
            >
              <i class="fas fa-heart" />
              <span>{{ likes }}</span>
            </div>
          </div>
        </template>
      </previewer>
    </div>

    <div class="col-md-4">
      <div class="card card-primary">
        <div class="card-header">
          <h3 v-t="'skinlib.show.detail'" class="card-title" />
        </div>
        <div class="card-body">
          <table class="table">
            <tbody>
              <tr>
                <td v-t="'skinlib.show.name'" />
                <td>
                  {{ name.length > 15 ? `${name.slice(0, 15)}...` : name }}
                  <small v-if="hasEditPermission">
                    <a v-t="'skinlib.show.edit'" href="#" @click="changeTextureName" />
                  </small>
                </td>
              </tr>
              <tr>
                <td v-t="'skinlib.show.model'" />
                <td>
                  <span v-if="type === 'cape'">{{ $t('general.cape') }}</span>
                  <span v-else>{{ type }}</span>
                  <small v-if="hasEditPermission">
                    <a v-t="'skinlib.show.edit'" href="#" @click="changeModel" />
                  </small>
                </td>
              </tr>
              <tr>
                <td>Hash</td>
                <td>
                  <span :title="hash">{{ hash.slice(0, 15) }}...</span>
                </td>
              </tr>
              <tr>
                <td v-t="'skinlib.show.size'" />
                <td>{{ size }} KB</td>
              </tr>
              <tr>
                <td v-t="'skinlib.show.uploader'" />
                <td v-if="uploaderNickName !== null">
                  <a
                    :href="`${baseUrl}skinlib?filter=${type === 'cape' ? 'cape' : 'skin'}&uploader=${uploader}`"
                  >{{ uploaderNickName }}</a>
                </td>
                <td v-else><span v-t="'general.unexistent-user'" /></td>
              </tr>
              <tr>
                <td v-t="'skinlib.show.upload-at'" />
                <td>{{ uploadAt }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div v-if="hasEditPermission" class="card card-warning">
        <div class="card-header">
          <h3 v-t="'admin.operationsTitle'" class="card-title" />
        </div>
        <div class="card-body">
          <p v-t="'skinlib.show.manage-notice'" />
        </div>

        <div class="card-footer">
          <div class="container d-flex justify-content-between">
            <button class="btn btn-warning" @click="togglePrivacy">
              {{ $t(togglePrivacyText) }}
            </button>
            <button class="btn btn-danger" @click="deleteTexture">
              {{ $t('skinlib.show.delete-texture') }}
            </button>
          </div>
        </div>
      </div>
    </div>

    <apply-to-player-dialog
      ref="useAs"
      :allow-add="false"
      :skin="type !== 'cape' ? tid : 0"
      :cape="type === 'cape' ? tid : 0"
    />
  </div>
</template>

<script>
import setAsAvatar from '../../components/mixins/setAsAvatar'
import addClosetItem from '../../components/mixins/addClosetItem'
import removeClosetItem from '../../components/mixins/removeClosetItem'
import emitMounted from '../../components/mixins/emitMounted'
import ApplyToPlayerDialog from '../../components/ApplyToPlayerDialog.vue'

export default {
  name: 'Show',
  components: {
    ApplyToPlayerDialog,
    Previewer: () => import('../../components/Previewer.vue'),
  },
  mixins: [
    emitMounted,
    addClosetItem,
    removeClosetItem,
    setAsAvatar,
  ],
  props: {
    baseUrl: {
      type: String,
      default: document.baseURI,
    },
  },
  data() {
    return {
      tid: +this.$route[1],
      name: '',
      type: 'steve',
      likes: 0,
      hash: '',
      uploader: 0,
      size: 0,
      uploadAt: '',
      public: true,
      liked: blessing.extra.inCloset,
      canBeDownloaded: blessing.extra.download,
      currentUid: blessing.extra.currentUid,
      admin: blessing.extra.admin,
      uploaderNickName: blessing.extra.nickname,
      reportScore: blessing.extra.report,
    }
  },
  computed: {
    anonymous() {
      return !this.currentUid
    },
    hasEditPermission() {
      return this.uploader === this.currentUid || this.admin
    },
    togglePrivacyText() {
      return this.public ? 'skinlib.setAsPrivate' : 'skinlib.setAsPublic'
    },
    textureUrl() {
      return `${this.baseUrl}textures/${this.hash}`
    },
  },
  beforeMount() {
    this.fetchData()
  },
  methods: {
    async fetchData() {
      const { data = {} } = await this.$http.get(`/skinlib/info/${this.tid}`)
      Object.assign(this.$data, data)
      this.uploadAt = data.upload_at
    },
    async addToCloset() {
      this.$once('like-toggled', () => {
        this.liked = true
        this.likes += 1
      })
      await this.addClosetItem()
    },
    async removeFromCloset() {
      this.$once('item-removed', () => {
        this.liked = false
        this.likes -= 1
      })
      await this.removeClosetItem()
    },
    download() {
      const a = document.createElement('a')
      a.href = `${this.baseUrl}raw/${this.tid}.png`
      a.download = `${this.name}.png`
      const event = new MouseEvent('click')
      a.dispatchEvent(event)
    },
    async changeTextureName() {
      let value
      try {
        ({ value } = await this.$prompt(this.$t('skinlib.setNewTextureName'), {
          inputValue: this.name,
          inputValidator: name => !!name || this.$t('skinlib.emptyNewTextureName'),
        }))
      } catch {
        return
      }

      const { code, message } = await this.$http.post(
        '/skinlib/rename',
        { tid: this.tid, new_name: value },
      )
      if (code === 0) {
        this.name = value
        this.$message.success(message)
      } else {
        this.$message.error(message)
      }
    },
    async changeModel() {
      const h = this.$createElement
      const vnode = h('div', null, [
        h('span', null, this.$t('skinlib.setNewTextureModel')),
        h('select', { attrs: { selectedIndex: 0 } }, [
          h('option', { attrs: { value: 'steve' } }, 'Steve'),
          h('option', { attrs: { value: 'alex' } }, 'Alex'),
          h('option', { attrs: { value: 'cape' } }, this.$t('general.cape')),
        ]),
      ])
      try {
        await this.$msgbox({
          message: vnode,
          showCancelButton: true,
        })
      } catch {
        return
      }
      const value = ['steve', 'alex', 'cape'][vnode.children[1].elm.selectedIndex]

      const { code, message } = await this.$http.post(
        '/skinlib/model',
        { tid: this.tid, model: value },
      )
      if (code === 0) {
        this.type = value
        this.$message.success(message)
      } else {
        this.$message.warning(message)
      }
    },
    async togglePrivacy() {
      try {
        await this.$confirm(
          this.public
            ? this.$t('skinlib.setPrivateNotice')
            : this.$t('skinlib.setPublicNotice'),
          { type: 'warning' },
        )
      } catch {
        return
      }

      const { code, message } = await this.$http.post(
        '/skinlib/privacy',
        { tid: this.tid },
      )
      if (code === 0) {
        this.$message.success(message)
        this.public = !this.public
      } else {
        this.$message.warning(message)
      }
    },
    async deleteTexture() {
      try {
        await this.$confirm(
          this.$t('skinlib.deleteNotice'),
          { type: 'warning' },
        )
      } catch {
        return
      }

      const { code, message } = await this.$http.post(
        '/skinlib/delete',
        { tid: this.tid },
      )
      if (code === 0) {
        this.$message.success(message)
        setTimeout(() => (window.location = `${this.baseUrl}skinlib`), 1000)
      } else {
        this.$message.warning(message)
      }
    },
    async report() {
      const prompt = (() => {
        if (this.reportScore > 0) {
          return this.$t('skinlib.report.positive', { score: this.reportScore })
        } else if (this.reportScore < 0) {
          return this.$t('skinlib.report.negative', { score: -this.reportScore })
        }
        return ''
      })()
      let reason
      try {
        ({ value: reason } = await this.$prompt(prompt, {
          title: this.$t('skinlib.report.title'),
          inputPlaceholder: this.$t('skinlib.report.reason'),
        }))
      } catch {
        return
      }

      const { code, message } = await this.$http.post(
        '/skinlib/report',
        { tid: this.tid, reason },
      )
      if (code === 0) {
        this.$message.success(message)
      } else {
        this.$message.warning(message)
      }
    },
    fetchPlayersList() {
      this.$refs.useAs.fetchList()
    },
  },
}
</script>

<style lang="stylus">
.table > tbody > tr > td
  border-top 0
</style>
