// resources/assets/src/views/skinlib/Upload.vue
<template>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <div class="card card-primary">
          <div class="card-body">
            <div class="form-group">
              <label v-t="'skinlib.upload.texture-name'" for="name" />
              <input
                v-model="name"
                type="text"
                :placeholder="textureNameRule"
                class="form-control"
              >
            </div>

            <div class="form-group">
              <label v-t="'skinlib.upload.texture-type'" />
              <br>
              <label class="mr-2">
                <input
                  v-model="type"
                  type="radio"
                  name="type"
                  value="steve"
                >
                Steve
              </label>
              <label class="mr-2">
                <input
                  v-model="type"
                  type="radio"
                  name="type"
                  value="alex"
                >
                Alex
              </label>
              <label class="mr-2">
                <input
                  v-model="type"
                  type="radio"
                  name="type"
                  value="cape"
                >
                {{ $t('general.cape') }}
              </label>
            </div>

            <div class="form-group">
              <label v-t="'skinlib.upload.select-file'" for="file" />
              <div class="file-dnd">
                <img v-if="hasFile" :src="texture" :width="width2d">
                <h3 v-else v-t="'skinlib.upload.dropZone'" />
              </div>
              <file-upload
                ref="upload"
                v-model="files"
                extensions="png"
                accept="image/png,image/x-png"
                drop=".file-dnd"
                @input-file="inputFile"
              >
                <button class="btn btn-primary">
                  {{ $t('skinlib.upload.select-file') }}
                </button>
              </file-upload>
              <button
                v-show="hasFile"
                class="btn btn-danger float-right"
                data-test="remove"
                @click="remove"
              >
                <i class="fas fa-trash-alt" />
                {{ $t('skinlib.upload.remove') }}
              </button>
            </div>

            <!-- eslint-disable-next-line vue/no-v-html -->
            <div v-if="contentPolicy" class="callout callout-warning" v-html="contentPolicy" />
          </div>

          <div class="card-footer">
            <div class="container pl-0 pr-0 d-flex justify-content-between">
              <label
                class="mt-2"
                :title="$t('skinlib.upload.privacy-notice')"
                data-toggle="tooltip"
              >
                <input v-model="isPrivate" type="checkbox">
                {{ $t('skinlib.upload.set-as-private') }}
              </label>
              <button v-if="uploading" class="btn btn-success" disabled>
                <i class="fa fa-spinner fa-spin" /> {{ $t('skinlib.uploading') }}
              </button>
              <button v-else class="btn btn-success" @click="upload">
                {{ $t('skinlib.upload.button') }}
              </button>
            </div>
            <div v-if="hasFile" class="callout callout-info bottom-notice">
              <p>{{ $t('skinlib.upload.cost', { score: scoreCost }) }}</p>
            </div>
            <div v-if="isPrivate" class="callout callout-info bottom-notice">
              <p>{{ privacyNotice }}</p>
            </div>
            <div v-if="!isPrivate && award" class="callout callout-success bottom-notice">
              <p>{{ $t('skinlib.upload.award', { score: award }) }}</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <previewer
          :skin="type !== 'cape' ? texture : ''"
          :cape="type === 'cape' ? texture : ''"
          :model="type"
        />
      </div>
    </div>
  </div>
</template>

<script>
import FileUpload from 'vue-upload-component'
import { isSlimSkin } from 'skinview3d'
import emitMounted from '../../components/mixins/emitMounted'
import { toast } from '../../scripts/notify'

export default {
  name: 'Upload',
  components: {
    Previewer: () => import('../../components/Previewer.vue'),
    FileUpload,
  },
  mixins: [
    emitMounted,
  ],
  data() {
    return {
      name: '',
      type: 'steve',
      isPrivate: false,
      files: [],
      texture: '',
      uploading: false,
      textureNameRule: blessing.extra.rule,
      privacyNotice: blessing.extra.privacyNotice,
      scorePublic: blessing.extra.scorePublic,
      scorePrivate: blessing.extra.scorePrivate,
      award: blessing.extra.award,
      contentPolicy: blessing.extra.contentPolicy,
      width2d: 64,
    }
  },
  computed: {
    scoreCost() {
      const size = Math.round(this.files[0].size / 1024) || 1
      return size * (this.isPrivate ? this.scorePrivate : this.scorePublic)
    },
    hasFile() {
      return this.files[0]
    },
  },
  methods: {
    async upload() {
      if (!this.hasFile) {
        toast.error(this.$t('skinlib.emptyUploadFile'))
        return
      }

      if (!this.name) {
        toast.error(this.$t('skinlib.emptyTextureName'))
        return
      }

      if (!/image\/(x-)?png/.test(this.files[0].type)) {
        toast.error(this.$t('skinlib.fileExtError'))
        return
      }

      const data = new FormData()
      data.append('name', this.name)
      data.append('type', this.type)
      data.append('file', this.files[0].file, this.files[0].name)
      data.append('public', !this.isPrivate)

      this.uploading = true
      const {
        code, message, data: { tid } = { tid: 0 },
      } = await this.$http.post('/skinlib/upload', data)
      if (code === 0) {
        window.location = `${blessing.base_url}/skinlib/show/${tid}`
      } else {
        toast.error(message)
        this.uploading = false
      }
    },
    inputFile(file) {
      if (!file) {
        return
      }

      if (!this.name) {
        const matched = /(.*)\.png$/i.exec(file.name)
        this.name = matched ? matched[1] : file.name
      }
      this.texture = URL.createObjectURL(file.file)

      const image = new Image()
      image.src = this.texture
      image.onload = () => {
        this.width2d = image.width > 400 ? 400 : image.width
        this.type = isSlimSkin(image) ? 'alex' : 'steve'
      }
    },
    remove() {
      this.$refs.upload.clear()
      this.texture = ''
    },
  },
}
</script>

<style lang="stylus">
.file-dnd
  min-height 256px
  margin-bottom 15px
  border 1px solid #ddd
  border-radius 2px
  display flex
  justify-content center
  align-items center

  h3
    color #aaa

.bottom-notice
  margin-top 10px
</style>

// resources/assets/src/views/skinlib/Upload.tsx
import React, { useState } from 'react'
import ReactDOM from 'react-dom'
import { hot } from 'react-hot-loader/root'
import { t } from '@/scripts/i18n'
import useBlessingExtra from '@/scripts/hooks/useBlessingExtra'
import useMount from '@/scripts/hooks/useMount'
import * as fetch from '@/scripts/net'
import { showModal, toast } from '@/scripts/notify'
import { isAlex } from '@/scripts/textureUtils'
import { TextureType } from '@/scripts/types'
import urls from '@/scripts/urls'
import FileInput from '@/components/FileInput'
import ViewerSkeleton from '@/components/ViewerSkeleton'

const Previewer = React.lazy(() => import('@/components/Viewer'))

const Upload: React.FC = () => {
  const [name, setName] = useState('')
  const [type, setType] = useState(TextureType.Steve)
  const [isPrivate, setIsPrivate] = useState(false)
  const [isUploading, setIsUploading] = useState(false)
  const [file, setFile] = useState<File | null>(null)
  const [texture, setTexture] = useState('')
  const nameRule = useBlessingExtra<string>('rule')
  const contentPolicy = useBlessingExtra<string>('contentPolicy')
  const privacyNotice = useBlessingExtra<string>('privacyNotice')
  const award = useBlessingExtra<number>('award')
  const currentScore = useBlessingExtra<number>('score', 0)
  const scorePublic = useBlessingExtra<number>('scorePublic')
  const scorePrivate = useBlessingExtra<number>('scorePrivate')
  const closetItemCost = useBlessingExtra<number>('closetItemCost')

  const container = useMount('#previewer')

  const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setName(event.target.value)
  }

  const handleTypeChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setType(event.target.value as TextureType)
  }

  const handlePrivateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setIsPrivate(event.target.checked)
  }

  const handleFileChange = async (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    const files = event.target.files!
    const [file] = files
    if (file) {
      setFile(file)
      if (!name && file.name.endsWith('.png')) {
        setName(file.name.slice(0, file.name.length - 4))
      }
      const texture = URL.createObjectURL(file)
      setTexture(texture)
      if (type !== TextureType.Cape) {
        setType((await isAlex(texture)) ? TextureType.Alex : TextureType.Steve)
      }
    }
  }

  const handleUpload = async () => {
    if (!file) {
      toast.error(t('skinlib.emptyUploadFile'))
      return
    }

    if (!name) {
      toast.error(t('skinlib.emptyTextureName'))
      return
    }

    if (file.type !== 'image/png' && file.type !== 'image/x-png') {
      toast.error(t('skinlib.fileExtError'))
      return
    }

    const formData = new FormData()
    formData.append('name', name)
    formData.append('type', type)
    formData.append('file', file, file.name)
    formData.append('public', isPrivate ? '0' : '1')

    setIsUploading(true)
    const { code, message, data: { tid } = { tid: 0 } } = await fetch.post<
      fetch.ResponseBody<{ tid: number }>
    >(urls.texture.upload(), formData)
    setIsUploading(false)

    if (code === 0) {
      window.location.href = blessing.base_url + urls.skinlib.show(tid)
    } else if (code === 2) {
      try {
        await showModal({
          mode: 'confirm',
          text: message,
          okButtonText: t('user.viewInSkinlib'),
        })
        window.location.href = blessing.base_url + urls.skinlib.show(tid)
      } catch {
        //
      }
    } else {
      toast.error(message)
    }
  }

  const costRatio = isPrivate ? scorePrivate : scorePublic
  const size = file?.size ?? 0
  const scoreCost = Math.ceil(size / 1024) * costRatio + closetItemCost

  return (
    <>
      <div className="card card-primary">
        <div className="card-body">
          <div className="form-group">
            <label htmlFor="texture-name">
              {t('skinlib.upload.texture-name')}
            </label>
            <input
              className="form-control"
              id="texture-name"
              type="text"
              placeholder={nameRule}
              value={name}
              onChange={handleNameChange}
            />
          </div>
          <div className="form-group">
            <label>{t('skinlib.upload.texture-type')}</label>
            <br />
            <label className="mr-4">
              <input
                type="radio"
                className="mr-1"
                name="type"
                value="steve"
                checked={type === TextureType.Steve}
                onChange={handleTypeChange}
              />
              Steve
            </label>
            <label className="mr-4">
              <input
                type="radio"
                className="mr-1"
                name="type"
                value="alex"
                checked={type === TextureType.Alex}
                onChange={handleTypeChange}
              />
              Alex
            </label>
            <label className="mr-4">
              <input
                type="radio"
                className="mr-1"
                name="type"
                value="cape"
                checked={type === TextureType.Cape}
                onChange={handleTypeChange}
              />
              {t('general.cape')}
            </label>
          </div>
          <FileInput
            file={file}
            accept="image/png, image/x-png"
            onChange={handleFileChange}
          />

          {contentPolicy && (
            <div
              className="callout callout-warning"
              dangerouslySetInnerHTML={{ __html: contentPolicy }}
            />
          )}
        </div>
        <div className="card-footer">
          <div className="container px-0 d-flex justify-content-between">
            <label
              className="mt-2"
              htmlFor="is-private"
              title={t('skinlib.upload.privacy-notice')}
            >
              <input
                type="checkbox"
                id="is-private"
                className="mr-1"
                checked={isPrivate}
                onChange={handlePrivateChange}
              />
              {t('skinlib.upload.set-as-private')}
            </label>
            <button
              className="btn btn-success"
              disabled={isUploading}
              onClick={handleUpload}
            >
              {isUploading ? (
                <>
                  <i className="fas fa-spinner fa-spin mr-1" />
                  <span>{t('skinlib.uploading')}</span>
                </>
              ) : (
                t('skinlib.upload.button')
              )}
            </button>
          </div>
          {file && (
            <div
              className={`callout callout-${
                currentScore > scoreCost ? 'success' : 'danger'
              } mt-3`}
            >
              <div>{t('skinlib.upload.cost', { score: scoreCost })}</div>
              <div>
                {t('user.cur-score')}
                <span className="ml-1">{currentScore}</span>
              </div>
            </div>
          )}
          {isPrivate && (
            <div className="callout callout-info mt-3">{privacyNotice}</div>
          )}
          {!isPrivate && award > 0 && (
            <div className="callout callout-success mt-3">
              {t('skinlib.upload.award', { score: award })}
            </div>
          )}
        </div>
      </div>
      {ReactDOM.createPortal(
        <React.Suspense fallback={<ViewerSkeleton />}>
          <Previewer
            skin={type !== TextureType.Cape ? texture : undefined}
            cape={type === TextureType.Cape ? texture : undefined}
            isAlex={type === TextureType.Alex}
          />
        </React.Suspense>,
        container,
      )}
    </>
  )
}

export default hot(Upload)
