// resources/assets/src/components/skinlib/Upload.vue
<template>
    <section class="content">
        <div class="row">
            <div class="col-md-6">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="name" v-t="'skinlib.upload.texture-name'"></label>
                            <input
                                v-model="name"
                                class="form-control"
                                type="text"
                                :placeholder="textureNameRule"
                            />
                        </div>

                        <div class="form-group">
                            <label v-t="'skinlib.upload.texture-type'"></label>
                            <br>
                            <label>
                                <input
                                    type="radio"
                                    v-model="type"
                                    name="type"
                                    value="steve"
                                    checked
                                > Steve
                            </label>&nbsp;
                            <label>
                                <input
                                    type="radio"
                                    v-model="type"
                                    name="type"
                                    value="alex"
                                > Alex
                            </label>&nbsp;
                            <label>
                                <input
                                    type="radio"
                                    v-model="type"
                                    name="type"
                                    value="cape"
                                > {{ $t('general.cape') }}
                            </label>

                        </div>

                        <div class="form-group">
                            <label for="file" v-t="'skinlib.upload.select-file'"></label>
                            <div class="file-dnd">
                                <img v-if="hasFile" :src="texture" :width="width2d" />
                                <h3 v-else v-t="'skinlib.upload.dropZone'"></h3>
                            </div>
                            <file-upload
                                v-model="files"
                                ref="upload"
                                extensions="png"
                                accept="image/png,image/x-png"
                                drop=".file-dnd"
                                @input-file="inputFile"
                            >
                                <span class="btn btn-primary">
                                    {{ $t('skinlib.upload.select-file') }}
                                </span>
                            </file-upload>
                            <button
                                v-show="hasFile"
                                class="btn btn-default pull-right"
                                @click="remove"
                            >
                                <i class="fas fa-trash-alt"></i>
                                {{ $t('skinlib.upload.remove') }}
                            </button>
                        </div>

                        <div class="callout callout-info" v-if="isPrivate">
                            <p>{{ privacyNotice }}</p>
                        </div>
                    </div><!-- /.box-body -->

                    <div class="box-footer">
                        <label
                            for="private"
                            class="pull-right"
                            :title="$t('skinlib.upload.privacy-notice')"
                            data-placement="top"
                            data-toggle="tooltip"
                        >
                            <input v-model="isPrivate" type="checkbox"> {{ $t('skinlib.upload.set-as-private') }}
                        </label>
                        <button v-if="uploading" class="btn btn-primary" disabled>
                            <i class="fa fa-spinner fa-spin"></i> {{ $t('skinlib.uploading') }}
                        </button>
                        <button v-else @click="upload" class="btn btn-primary">
                            {{ $t('skinlib.upload.button') }}
                        </button>
                        &nbsp; {{ hasFile && $t('skinlib.upload.cost', { score: scoreCost }) }}
                    </div>
                </div><!-- /.box -->
            </div>
            <div class="col-md-6">
                <previewer
                    :skin="type !== 'cape' && texture"
                    :cape="type === 'cape' ? texture : ''"
                ></previewer>
            </div>
        </div>

    </section>
</template>

<script>
import FileUpload from 'vue-upload-component';
import toastr from 'toastr';
import { swal } from '../../js/notify';

export default {
    name: 'Upload',
    components: {
        Previewer: () => import('../common/Previewer'),
        FileUpload
    },
    data() {
        return {
            name: '',
            type: 'steve',
            isPrivate: false,
            files: [],
            texture: '',
            uploading: false,
            textureNameRule: blessing.extra.rule,
            privacyNotice: blessing.extra.privacyNotice,
            scorePublic: blessing.extra.scorePublic,
            scorePrivate: blessing.extra.scorePrivate,
            width2d: 64,
        };
    },
    computed: {
        scoreCost() {
            const size = Math.round(this.files[0].size / 1024) || 1;
            return size * (this.isPrivate ? this.scorePrivate : this.scorePublic);
        },
        hasFile() {
            return this.files[0];
        }
    },
    methods: {
        async upload() {
            if (!this.hasFile) {
                toastr.info(this.$t('skinlib.emptyUploadFile'));
                return;
            }

            if (!this.name) {
                toastr.info(this.$t('skinlib.emptyTextureName'));
                return;
            }

            if (!/image\/(x-)?png/.test(this.files[0].type)) {
                toastr.info(this.$t('skinlib.fileExtError'));
                return;
            }

            const data = new FormData();
            data.append('name', this.name);
            data.append('type', this.type);
            data.append('file', this.files[0].file, this.files[0].name);
            data.append('public', !this.isPrivate);

            this.uploading = true;
            const { errno, msg, tid } = await this.$http.post('/skinlib/upload', data);
            if (errno === 0) {
                await swal({ type: 'success', text: msg });
                toastr.info(this.$t('skinlib.redirecting'));
                setTimeout(() => {
                    window.location = (`${blessing.base_url}/skinlib/show/${tid}`);
                }, 1000);
            } else {
                await swal({ type: 'warning', text: msg });
                this.uploading = false;
            }
        },
        inputFile(file) {
            if (!file) return;

            if (!this.name) {
                const matched = /(.*)\.png$/i.exec(file.name);
                this.name = matched ? matched[1] : file.name;
            }
            this.texture = URL.createObjectURL(file.file);

            const image = new Image();
            image.src = this.texture;
            image.onload = () => this.width2d = image.width > 400 ? 400 : image.width;
        },
        remove() {
            this.$refs.upload.clear();
            this.texture = '';
        }
    }
};
</script>

<style lang="stylus">
.file-dnd {
    min-height: 256px;
    margin-bottom: 15px;
    border: 1px solid #ddd;
    border-radius: 2px;
    display: flex;
    justify-content: center;
    align-items: center;

    h3 {
        color: #aaa;
    }
}
</style>

// resources/assets/src/views/skinlib/Upload.tsx
import React, { useState } from 'react'
import ReactDOM from 'react-dom'
import { hot } from 'react-hot-loader/root'
import { t } from '@/scripts/i18n'
import useBlessingExtra from '@/scripts/hooks/useBlessingExtra'
import useMount from '@/scripts/hooks/useMount'
import * as fetch from '@/scripts/net'
import { showModal, toast } from '@/scripts/notify'
import { isAlex } from '@/scripts/textureUtils'
import { TextureType } from '@/scripts/types'
import FileInput from '@/components/FileInput'
import ViewerSkeleton from '@/components/ViewerSkeleton'

const Previewer = React.lazy(() => import('@/components/Viewer'))

const Upload: React.FC = () => {
  const [name, setName] = useState('')
  const [type, setType] = useState<TextureType>('steve')
  const [isPrivate, setIsPrivate] = useState(false)
  const [isUploading, setIsUploading] = useState(false)
  const [file, setFile] = useState<File | null>(null)
  const [texture, setTexture] = useState('')
  const nameRule = useBlessingExtra<string>('rule')
  const contentPolicy = useBlessingExtra<string>('contentPolicy')
  const privacyNotice = useBlessingExtra<string>('privacyNotice')
  const award = useBlessingExtra<number>('award')
  const scorePublic = useBlessingExtra<number>('scorePublic')
  const scorePrivate = useBlessingExtra<number>('scorePrivate')
  const closetItemCost = useBlessingExtra<number>('closetItemCost')

  const container = useMount('#previewer')

  const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setName(event.target.value)
  }

  const handleTypeChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setType(event.target.value as TextureType)
  }

  const handlePrivateChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setIsPrivate(event.target.checked)
  }

  const handleFileChange = async (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    const files = event.target.files!
    const [file] = files
    if (file) {
      setFile(file)
      if (!name && file.name.endsWith('.png')) {
        setName(file.name.slice(0, file.name.length - 4))
      }
      const texture = URL.createObjectURL(file)
      setTexture(texture)
      if (type !== 'cape') {
        setType((await isAlex(texture)) ? 'alex' : 'steve')
      }
    }
  }

  const handleUpload = async () => {
    if (!file) {
      toast.error(t('skinlib.emptyUploadFile'))
      return
    }

    if (!name) {
      toast.error(t('skinlib.emptyTextureName'))
      return
    }

    if (file.type !== 'image/png' && file.type !== 'image/x-png') {
      toast.error(t('skinlib.fileExtError'))
      return
    }

    const formData = new FormData()
    formData.append('name', name)
    formData.append('type', type)
    formData.append('file', file, file.name)
    formData.append('public', (!isPrivate).toString())

    setIsUploading(true)
    const { code, message, data: { tid } = { tid: 0 } } = await fetch.post<
      fetch.ResponseBody<{ tid: number }>
    >('/skinlib/upload', formData)
    setIsUploading(false)

    if (code === 0) {
      window.location.href = `${blessing.base_url}/skinlib/show/${tid}`
    } else if (code === 2) {
      try {
        await showModal({
          mode: 'confirm',
          text: message,
          okButtonText: t('user.viewInSkinlib'),
        })
        window.location.href = `${blessing.base_url}/skinlib/show/${tid}`
      } catch {
        //
      }
    } else {
      toast.error(message)
    }
  }

  const costRatio = isPrivate ? scorePrivate : scorePublic
  const size = file?.size ?? 0
  const scoreCost = (~~(size / 1024) || 1) * costRatio + closetItemCost

  return (
    <>
      <div className="card card-primary">
        <div className="card-body">
          <div className="form-group">
            <label htmlFor="texture-name">
              {t('skinlib.upload.texture-name')}
            </label>
            <input
              className="form-control"
              id="texture-name"
              type="text"
              placeholder={nameRule}
              value={name}
              onChange={handleNameChange}
            />
          </div>
          <div className="form-group">
            <label>{t('skinlib.upload.texture-type')}</label>
            <br />
            <label className="mr-4">
              <input
                type="radio"
                className="mr-1"
                name="type"
                value="steve"
                checked={type === 'steve'}
                onChange={handleTypeChange}
              />
              Steve
            </label>
            <label className="mr-4">
              <input
                type="radio"
                className="mr-1"
                name="type"
                value="alex"
                checked={type === 'alex'}
                onChange={handleTypeChange}
              />
              Alex
            </label>
            <label className="mr-4">
              <input
                type="radio"
                className="mr-1"
                name="type"
                value="cape"
                checked={type === 'cape'}
                onChange={handleTypeChange}
              />
              {t('general.cape')}
            </label>
          </div>
          <FileInput
            file={file}
            accept="image/png, image/x-png"
            onChange={handleFileChange}
          />

          {contentPolicy && (
            <div
              className="callout callout-warning"
              dangerouslySetInnerHTML={{ __html: contentPolicy }}
            />
          )}
        </div>
        <div className="card-footer">
          <div className="container px-0 d-flex justify-content-between">
            <label
              className="mt-2"
              htmlFor="is-private"
              title={t('skinlib.upload.privacy-notice')}
            >
              <input
                type="checkbox"
                id="is-private"
                className="mr-1"
                checked={isPrivate}
                onChange={handlePrivateChange}
              />
              {t('skinlib.upload.set-as-private')}
            </label>
            <button
              className="btn btn-success"
              disabled={isUploading}
              onClick={handleUpload}
            >
              {isUploading ? (
                <>
                  <i className="fas fa-spinner fa-spin mr-1" />
                  <span>{t('skinlib.uploading')}</span>
                </>
              ) : (
                t('skinlib.upload.button')
              )}
            </button>
          </div>
          {file && (
            <div className="callout callout-success mt-3">
              <p>{t('skinlib.upload.cost', { score: scoreCost })}</p>
            </div>
          )}
          {isPrivate && (
            <div className="callout callout-info mt-3">
              <p>{privacyNotice}</p>
            </div>
          )}
          {!isPrivate && award > 0 && (
            <div className="callout callout-success mt-3">
              <p>{t('skinlib.upload.award', { score: award })}</p>
            </div>
          )}
        </div>
      </div>
      {ReactDOM.createPortal(
        <React.Suspense fallback={<ViewerSkeleton />}>
          <Previewer
            skin={type !== 'cape' ? texture : undefined}
            cape={type === 'cape' ? texture : undefined}
            isAlex={type === 'alex'}
          />
        </React.Suspense>,
        container,
      )}
    </>
  )
}

export default hot(Upload)
