// resources/assets/src/components/Captcha.tsx
import React from 'react'
import Reaptcha from 'reaptcha'
import { emit, on } from '@/scripts/event'
import { t } from '@/scripts/i18n'
import styles from './Captcha.module.scss'

const eventId = Symbol()

type State = {
  value: string
  time: number
  sitekey: string
  invisible: boolean
}

class Captcha extends React.Component<{}, State> {
  state: State
  ref: React.MutableRefObject<Reaptcha | null>

  constructor(props: {}) {
    super(props)
    this.state = {
      value: '',
      time: Date.now(),
      sitekey: blessing.extra.recaptcha,
      invisible: blessing.extra.invisible,
    }
    this.ref = React.createRef()
  }

  execute = async () => {
    const recaptcha = this.ref.current
    if (recaptcha && this.state.invisible) {
      return new Promise<string>(resolve => {
        const off = on(eventId, (value: string) => {
          resolve(value)
          off()
        })
        recaptcha.execute()
      })
    }
    return this.state.value
  }

  reset = () => {
    const recaptcha = this.ref.current
    if (recaptcha) {
      recaptcha.reset()
    } else {
      this.setState({ time: Date.now() })
    }
  }

  handleValueChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    this.setState({ value: event.target.value })
  }

  handleVerify = (value: string) => {
    emit(eventId, value)
    this.setState({ value })
  }

  handleRefresh = () => {
    this.setState({ time: Date.now() })
  }

  render() {
    return this.state.sitekey ? (
      <div className="mb-2">
        <Reaptcha
          ref={this.ref}
          sitekey={this.state.sitekey}
          size={this.state.invisible ? 'invisible' : 'normal'}
          onVerify={this.handleVerify}
        />
      </div>
    ) : (
      <div className="d-flex">
        <div className="form-group mb-3 mr-2">
          <input
            type="text"
            className="form-control"
            placeholder={t('auth.captcha')}
            required
            value={this.state.value}
            onChange={this.handleValueChange}
          />
        </div>
        <img
          src={`${blessing.base_url}/auth/captcha?v=${this.state.time}`}
          alt={t('auth.captcha')}
          className={styles.captcha}
          height={34}
          title={t('auth.change-captcha')}
          onClick={this.handleRefresh}
        />
      </div>
    )
  }
}

export default Captcha

// resources/assets/src/components/Captcha.vue
<template>
  <div v-if="recaptcha" class="row">
    <div class="d-block ml-2 pb-3">
      <vue-recaptcha
        ref="recaptcha"
        :size="invisible ? 'invisible' : ''"
        :sitekey="recaptcha"
        @verify="onVerify"
      />
    </div>
  </div>
  <div v-else class="d-flex">
    <div class="form-group mb-3 mr-2">
      <input
        ref="captcha"
        v-model="value"
        type="text"
        class="form-control"
        :placeholder="$t('auth.captcha')"
        required
      >
    </div>
    <div>
      <img
        class="captcha"
        :src="`${baseUrl}/auth/captcha?v=${time}`"
        alt="CAPTCHA"
        :title="$t('auth.change-captcha')"
        data-placement="top"
        data-toggle="tooltip"
        @click="refresh"
      >
    </div>
  </div>
</template>

<script>
import VueRecaptcha from 'vue-recaptcha'

export default {
  name: 'Captcha',
  components: {
    VueRecaptcha,
  },
  props: {
    baseUrl: {
      type: String,
      default: blessing.base_url,
    },
  },
  data() {
    return {
      value: '',
      time: Date.now(),
      recaptcha: blessing.extra.recaptcha,
      invisible: blessing.extra.invisible,
    }
  },
  methods: {
    execute() {
      return new Promise(resolve => {
        if (this.recaptcha && this.invisible) {
          this.$refs.recaptcha.$once('verify', resolve)
          this.$refs.recaptcha.execute()
        } else {
          resolve(this.value)
        }
      })
    },
    onVerify(response) {
      this.value = response
    },
    refresh() {
      if (this.recaptcha) {
        this.$refs.recaptcha.reset()
      } else {
        this.time = Date.now()
      }
    },
  },
}
</script>
