// resources/assets/src/views/user/Closet/ClosetItem.tsx
import React from 'react'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { showModal, toast } from '@/scripts/notify'
import { ClosetItem } from '@/scripts/types'
import styles from './ClosetItem.module.scss'

interface Props {
  item: ClosetItem
  selected: boolean
  onClick(item: ClosetItem): void
  onRename(): void
  onRemove(): void
}

const ClosetItem: React.FC<Props> = props => {
  const { item } = props

  const handleItemClick = () => {
    props.onClick(item)
  }

  const setAsAvatar = async () => {
    try {
      await showModal({
        title: t('user.setAvatar'),
        text: t('user.setAvatarNotice'),
      })
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/user/profile/avatar',
      { tid: item.tid },
    )
    if (code === 0) {
      toast.success(message)
      document
        .querySelectorAll<HTMLImageElement>('[alt="User Image"]')
        .forEach(el => (el.src += `?${new Date().getTime()}`))
    } else {
      toast.error(message)
    }
  }

  return (
    <div
      className={`card mr-3 mb-3 ${styles.item} ${
        props.selected ? 'shadow' : ''
      }`}
    >
      <div className={`card-body ${styles.bg}`} onClick={handleItemClick}>
        <img
          src={`${blessing.base_url}/preview/${item.tid}?height=150`}
          alt={item.pivot.item_name}
          className="card-img-top"
        />
      </div>
      <div className="card-footer pb-2 pt-2 pl-1 pr-1">
        <div className="container d-flex justify-content-between">
          <span className={styles.truncate} title={item.pivot.item_name}>
            {item.pivot.item_name}
          </span>
          <span className="d-inline-block drop-down">
            <span
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i className={`fas fa-cog text-gray ${styles.icon}`} />
            </span>
            <div className="dropdown-menu">
              <a href="#" className="dropdown-item" onClick={props.onRename}>
                {t('user.renameItem')}
              </a>
              <a href="#" className="dropdown-item" onClick={props.onRemove}>
                {t('user.removeItem')}
              </a>
              <a
                href={`${blessing.base_url}/skinlib/show/${item.tid}`}
                className="dropdown-item"
                target="_blank"
              >
                {t('user.viewInSkinlib')}
              </a>
              <a href="#" className="dropdown-item" onClick={setAsAvatar}>
                {t('user.setAsAvatar')}
              </a>
            </div>
          </span>
        </div>
      </div>
    </div>
  )
}

export default ClosetItem

// resources/assets/src/components/ClosetItem.vue
<template>
  <div class="card mr-3 mb-3 closet-item" :class="{ shadow: selected }">
    <div class="card-body texture-img" @click="$emit('select')">
      <img class="card-img-top" :src="previewLink">
    </div>
    <div class="card-footer pb-2 pt-2 pl-1 pr-1">
      <div class="container d-flex justify-content-between">
        <span data-test="name" :title="name">
          {{ textureName|truncate }} <small>({{ type }})</small>
        </span>

        <a class="float-right dropdown">
          <span
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <i class="fas fa-cog text-gray" />
          </span>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#" @click="rename">
              {{ $t('user.renameItem') }}
            </a>
            <a class="dropdown-item" href="#" @click="removeClosetItem">
              {{ $t('user.removeItem') }}
            </a>
            <a :href="linkToSkinlib" class="dropdown-item">
              {{ $t('user.viewInSkinlib') }}
            </a>
            <a
              v-if="type !== 'cape'"
              class="dropdown-item"
              href="#"
              @click="setAsAvatar"
            >{{ $t('user.setAsAvatar') }}</a>
          </div>
        </a>
      </div>
    </div>
  </div>
</template>

<script>
import setAsAvatar from './mixins/setAsAvatar'
import removeClosetItem from './mixins/removeClosetItem'
import truncateText from './mixins/truncateText'
import { showModal, toast } from '../scripts/notify'
import { truthy } from '../scripts/validators'

export default {
  name: 'ClosetItem',
  mixins: [
    removeClosetItem,
    setAsAvatar,
    truncateText,
  ],
  props: {
    tid: {
      type: Number,
      required: true,
    },
    type: {
      type: String,
      validator: value => ['steve', 'alex', 'cape'].includes(value),
    },
    name: {
      type: String,
      required: true,
    },
    selected: Boolean,
  },
  data() {
    return {
      textureName: this.name,
    }
  },
  computed: {
    previewLink() {
      return `${blessing.base_url}/preview/${this.tid}?height=150`
    },
    linkToSkinlib() {
      return `${blessing.base_url}/skinlib/show/${this.tid}`
    },
  },
  methods: {
    async rename() {
      let newTextureName
      try {
        ({ value: newTextureName } = await showModal(
          {
            mode: 'prompt',
            text: this.$t('user.renameClosetItem'),
            input: this.textureName,
            validator: truthy(this.$t('skinlib.emptyNewTextureName')),
          },
        ))
      } catch (_) {
        return
      }

      const { code, message } = await this.$http.post(
        `/user/closet/rename/${this.tid}`,
        { name: newTextureName },
      )
      if (code === 0) {
        this.textureName = newTextureName
        toast.success(message)
      } else {
        toast.error(message)
      }
    },
  },
}
</script>

<style lang="stylus">
.closet-item
  width 235px
  transition-property box-shadow
  transition-duration 0.3s
  &:hover
    box-shadow 0 .5rem 1rem rgba(0,0,0,.15)
    cursor pointer

  .fa-cog:hover
    color #000

.texture-img
  background #eff1f0
</style>
