// resources/assets/src/views/widgets/EmailVerification.tsx
import React, { useState } from 'react'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { toast } from '@/scripts/notify'

const EmailVerification: React.FC = () => {
  const [isSending, setIsSending] = useState(false)

  const send = async () => {
    setIsSending(true)
    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/user/email-verification',
    )
    if (code === 0) {
      toast.success(message)
    } else {
      toast.error(message)
    }
    setIsSending(false)
  }

  return (
    <div className="callout callout-info">
      <h4>
        <i className="fas fa-envelope"></i> {t('user.verification.title')}
      </h4>
      <p>
        {t('user.verification.message')}
        {isSending ? (
          <>
            <i className="fas fa-spin fa-spinner mr-1"></i>
            {t('user.verification.sending')}
          </>
        ) : (
          <a href="#" onClick={send}>
            {t('user.verification.resend')}
          </a>
        )}
      </p>
    </div>
  )
}

export default EmailVerification

// resources/assets/src/components/EmailVerification.vue
<template>
  <div v-if="!verified" class="callout callout-info">
    <h4><i class="fas fa-envelope" /> {{ $t('user.verification.title') }}</h4>
    <p>
      {{ $t('user.verification.message') }}
      <span v-if="pending">
        <i class="fas fa-spin fa-spinner" />
        {{ $t('user.verification.sending') }}
      </span>
      <a v-else href="#" @click="resend">
        {{ $t('user.verification.resend') }}
      </a>
    </p>
  </div>
</template>

<script>
import { toast } from '../scripts/notify'

export default {
  name: 'EmailVerification',
  data() {
    return {
      verified: !blessing.extra.unverified,
      pending: false,
    }
  },
  methods: {
    async resend() {
      this.pending = true
      const { code, message } = await this.$http.post('/user/email-verification')
      if (code === 0) {
        toast.success(message)
      } else {
        toast.error(message)
      }
      this.pending = false
    },
  },
}
</script>
