// resources/assets/src/components/Modal.tsx
import React, { useState, useEffect, useRef } from 'react'
import $ from 'jquery'
import 'bootstrap'
import { trans } from '../scripts/i18n'
import ModalHeader from './ModalHeader'
import ModalBody from './ModalBody'
import ModalFooter from './ModalFooter'

export type ModalOptions = {
  mode?: 'alert' | 'confirm' | 'prompt'
  show?: boolean
  title?: string
  text?: string
  dangerousHTML?: string
  input?: string
  placeholder?: string
  inputType?: string
  validator?(value: any): string | boolean | undefined
  choices?: { text: string; value: string }[]
  type?: string
  showHeader?: boolean
  center?: boolean
  okButtonText?: string
  okButtonType?: string
  cancelButtonText?: string
  cancelButtonType?: string
  flexFooter?: boolean
}

type Props = {
  id?: string
  children?: React.ReactNode
  footer?: React.ReactNode
  onConfirm?(payload: { value: string }): void
  onDismiss?(): void
}

export type ModalResult = {
  value: string
}

const Modal = React.forwardRef<HTMLDivElement, ModalOptions & Props>(
  (props, forwardedRef) => {
    const [hidden, setHidden] = useState(false)
    const [value, setValue] = useState(props.input!)
    const [valid, setValid] = useState(true)
    const [validatorMessage, setValidatorMessage] = useState('')
    const ref = (forwardedRef ??
      useRef<HTMLDivElement>(null)) as React.RefObject<HTMLDivElement>

    const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      setValue(event.target.value)
    }

    const confirm = () => {
      const { validator } = props
      if (typeof validator === 'function') {
        const result = validator(value)
        if (typeof result === 'string') {
          setValidatorMessage(result)
          setValid(false)
          return
        }
      }

      setHidden(true)
      props.onConfirm?.({ value })
      $(ref.current!).modal('hide')
    }

    const dismiss = () => {
      setHidden(true)
      props.onDismiss?.()
    }

    useEffect(() => {
      const onHide = () => {
        if (!hidden) {
          dismiss()
        }
      }
      const onHidden = () => setHidden(false)

      const el = $(ref.current!)
      el.on('hide.bs.modal', onHide).on('hidden.bs.modal', onHidden)

      return () => {
        el.off('hide.bs.modal', onHide).off('hidden.bs.modal', onHidden)
      }
    }, [hidden, props.onDismiss])

    return (
      <div
        id={props.id}
        className={`modal fade ${props.show ? 'show' : ''}`}
        tabIndex={-1}
        role="dialog"
        aria-hidden={!props.show}
        ref={ref}
      >
        <div
          className={`modal-dialog ${
            props.center ? 'modal-dialog-centered' : ''
          }`}
          role="document"
        >
          <div className={`modal-content bg-${props.type}`}>
            <ModalHeader
              show={props.showHeader}
              title={props.title}
              onDismiss={dismiss}
            />
            <ModalBody
              text={props.text}
              dangerousHTML={props.dangerousHTML}
              showInput={props.mode === 'prompt'}
              value={value}
              choices={props.choices}
              onChange={handleInputChange}
              inputType={props.inputType}
              placeholder={props.placeholder}
              invalid={!valid}
              validatorMessage={validatorMessage}
            >
              {props.children}
            </ModalBody>
            <ModalFooter
              showCancelButton={props.mode !== 'alert'}
              flexFooter={props.flexFooter}
              okButtonType={props.okButtonType}
              okButtonText={props.okButtonText}
              cancelButtonType={props.cancelButtonType}
              cancelButtonText={props.cancelButtonText}
              onConfirm={confirm}
              onDismiss={dismiss}
            >
              {props.footer}
            </ModalFooter>
          </div>
        </div>
      </div>
    )
  },
)

Modal.displayName = 'Modal'

Modal.defaultProps = {
  mode: 'confirm',
  title: trans('general.tip'),
  text: '',
  input: '',
  placeholder: '',
  inputType: 'text',
  type: 'default',
  showHeader: true,
  center: false,
  okButtonText: trans('general.confirm'),
  okButtonType: 'primary',
  cancelButtonText: trans('general.cancel'),
  cancelButtonType: 'secondary',
  flexFooter: false,
}

export default Modal

// resources/assets/src/components/Modal.vue
<template>
  <div
    :id="id"
    class="modal fade"
    tabindex="-1"
    role="dialog"
    aria-hidden="true"
  >
    <div class="modal-dialog" :class="{ 'modal-dialog-centered': center }" role="document">
      <div class="modal-content" :class="[`bg-${type}`]">
        <div v-if="showHeader" class="modal-header">
          <h5 class="modal-title">{{ title }}</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
            @click="dismiss"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <slot>
            <template v-if="text">
              <p v-for="(line, i) in lines" :key="i">{{ line }}</p>
            </template>
            <!-- eslint-disable-next-line vue/no-v-html -->
            <div v-else-if="dangerousHTML" v-html="dangerousHTML" />
            <template v-if="mode === 'prompt'">
              <div class="form-group">
                <input
                  v-model="value"
                  :type="inputType"
                  class="form-control"
                  :placeholder="placeholder"
                  @input="valid = true"
                >
              </div>
              <div v-if="!valid" class="alert alert-danger">
                <i class="icon far fa-times-circle" />
                {{ validatorMessage }}
              </div>
            </template>
          </slot>
        </div>
        <div class="modal-footer" :class="footerClasses">
          <slot name="footer">
            <button
              v-if="mode !== 'alert'"
              type="button"
              class="btn"
              :class="[`btn-${cancelButtonType}`]"
              data-dismiss="modal"
              @click="dismiss"
            >
              {{ cancelButtonText }}
            </button>
            <button
              type="button"
              class="btn"
              :class="[`btn-${okButtonType}`]"
              @click="confirm"
            >
              {{ okButtonText }}
            </button>
          </slot>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import $ from 'jquery'
import { trans } from '../scripts/i18n'

export default {
  name: 'Modal',
  props: {
    mode: {
      type: String,
      default: 'confirm',
      validator: value => ['alert', 'confirm', 'prompt'].includes(value),
    },
    id: {
      type: String,
    },
    title: {
      type: String,
      default: trans('general.tip'),
    },
    text: {
      type: String,
      default: '',
    },
    dangerousHTML: {
      type: String,
    },
    input: {
      type: String,
      default: '',
    },
    placeholder: {
      type: String,
    },
    inputType: {
      type: String,
      default: 'text',
    },
    validator: {
      type: Function,
    },
    type: {
      type: String,
      default: 'default',
    },
    showHeader: {
      type: Boolean,
      default: true,
    },
    center: {
      type: Boolean,
      default: false,
    },
    okButtonText: {
      type: String,
      default: trans('general.confirm'),
    },
    okButtonType: {
      type: String,
      default: 'primary',
    },
    cancelButtonText: {
      type: String,
      default: trans('general.cancel'),
    },
    cancelButtonType: {
      type: String,
      default: 'secondary',
    },
    flexFooter: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      hidden: false,
      value: this.input,
      valid: true,
      validatorMessage: '',
    }
  },
  computed: {
    lines() {
      return this.text.split(/\r?\n/)
    },
    footerClasses() {
      return {
        'd-flex': this.flexFooter,
        'justify-content-between': this.flexFooter,
      }
    },
  },
  mounted() {
    $(this.$el)
      .on('hide.bs.modal', () => {
        if (!this.hidden) {
          this.dismiss()
        }
      })
      .on('hidden.bs.modal', () => {
        this.hidden = false
      })
  },
  methods: {
    confirm() {
      if (typeof this.validator === 'function') {
        const result = this.validator(this.value)
        if (typeof result === 'string') {
          this.validatorMessage = result
          this.valid = false
          return
        }
      }

      this.hidden = true
      this.$emit('confirm', { value: this.value })
      $(this.$el).modal('hide')
    },
    dismiss() {
      this.hidden = true
      this.$emit('dismiss')
    },
  },
}
</script>
