// resources/assets/src/components/user/ClosetItem.vue
<template>
    <div class="item" :class="{ 'item-selected': selected }">
        <div class="item-body" @click="$emit('select')">
            <img :src="previewLink">
        </div>
        <div class="item-footer">
            <p class="texture-name">
                <span :title="name">{{ textureName }} <small>({{ type }})</small></span>
            </p>

            <a
                :href="linkToSkinlib"
                :title="$t('user.viewInSkinlib')"
                class="more"
                data-toggle="tooltip"
                data-placement="bottom"
            ><i class="fas fa-share"></i></a>
            <span
                :title="$t('general.more')"
                class="more"
                data-toggle="dropdown"
                aria-haspopup="true"
                id="more-button"
            ><i class="fas fa-cog"></i></span>

            <ul class="dropup dropdown-menu" aria-labelledby="more-button">
                <li><a @click="rename" v-t="'user.renameItem'"></a></li>
                <li><a @click="remove" v-t="'user.removeItem'"></a></li>
                <li><a @click="setAsAvatar" v-t="'user.setAsAvatar'"></a></li>
            </ul>
        </div>
    </div>
</template>

<script>
import { swal } from '../../js/notify';
import toastr from 'toastr';

export default {
    name: 'ClosetItem',
    props: {
        tid: {
            type: Number,
            required: true,
        },
        type: {
            type: String,
            validator: value => ['steve', 'alex', 'cape'].includes(value)
        },
        name: {
            type: String,
            required: true
        },
        selected: Boolean
    },
    data() {
        return {
            textureName: this.name
        };
    },
    computed: {
        previewLink() {
            return `${blessing.base_url}/preview/${this.tid}.png`;
        },
        linkToSkinlib() {
            return `${blessing.base_url}/skinlib/show/${this.tid}`;
        }
    },
    methods: {
        async rename() {
            const { value: newTextureName, dismiss } = await swal({
                title: this.$t('user.renameClosetItem'),
                input: 'text',
                inputValue: this.textureName,
                showCancelButton: true,
                inputValidator: value => !value && this.$t('skinlib.emptyNewTextureName')
            });
            if (dismiss) {
                return;
            }

            const { errno, msg } = await this.$http.post(
                '/user/closet/rename',
                { tid: this.tid, new_name: newTextureName }
            );

            if (errno === 0) {
                this.textureName = newTextureName;
                toastr.success(msg);
            } else {
                toastr.warning(msg);
            }
        },
        async remove() {
            const { dismiss } = await swal({
                text: this.$t('user.removeFromClosetNotice'),
                type: 'warning',
                showCancelButton: true
            });
            if (dismiss) {
                return;
            }

            const { errno, msg } = await this.$http.post(
                '/user/closet/remove',
                { tid: this.tid }
            );

            if (errno === 0) {
                this.$emit('item-removed', this.tid);
                swal({ type: 'success', text: msg });
            } else {
                toastr.warning(msg);
            }
        },
        async setAsAvatar() {
            const { dismiss } = await swal({
                title: this.$t('user.setAvatar'),
                text: this.$t('user.setAvatarNotice'),
                type: 'question',
                showCancelButton: true
            });
            if (dismiss) {
                return;
            }

            const { errno, msg } = await this.$http.post(
                '/user/profile/avatar',
                { tid: this.tid }
            );

            if (errno === 0) {
                toastr.success(msg);

                // Refresh avatars
                $('[alt="User Image"]').each(function () {
                    $(this).prop('src', $(this).attr('src') + '?' + new Date().getTime());
                });
            } else {
                toastr.warning(msg);
            }
        }
    }
};
</script>

// resources/assets/src/views/user/Closet/ClosetItem.tsx
import React from 'react'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { showModal, toast } from '@/scripts/notify'
import { ClosetItem } from '@/scripts/types'
import styles from './ClosetItem.module.scss'

interface Props {
  item: ClosetItem
  selected: boolean
  onClick(item: ClosetItem): void
  onRename(): void
  onRemove(): void
}

const ClosetItem: React.FC<Props> = props => {
  const { item } = props

  const handleItemClick = () => {
    props.onClick(item)
  }

  const setAsAvatar = async () => {
    try {
      await showModal({
        title: t('user.setAvatar'),
        text: t('user.setAvatarNotice'),
      })
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      '/user/profile/avatar',
      { tid: item.tid },
    )
    if (code === 0) {
      toast.success(message)
      document
        .querySelectorAll<HTMLImageElement>('[alt="User Image"]')
        .forEach(el => (el.src += `?${new Date().getTime()}`))
    } else {
      toast.error(message)
    }
  }

  return (
    <div
      className={`card mr-3 mb-3 ${styles.item} ${
        props.selected ? 'shadow' : ''
      }`}
    >
      <div className={`card-body ${styles.bg}`} onClick={handleItemClick}>
        <img
          src={`${blessing.base_url}/preview/${item.tid}?height=150`}
          alt={item.pivot.item_name}
          className="card-img-top"
        />
      </div>
      <div className="card-footer pb-2 pt-2 pl-1 pr-1">
        <div className="container d-flex justify-content-between">
          <span className={styles.truncate} title={item.pivot.item_name}>
            {item.pivot.item_name}
          </span>
          <span className="d-inline-block drop-down">
            <span
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i className={`fas fa-cog text-gray ${styles.icon}`} />
            </span>
            <div className="dropdown-menu">
              <a href="#" className="dropdown-item" onClick={props.onRename}>
                {t('user.renameItem')}
              </a>
              <a href="#" className="dropdown-item" onClick={props.onRemove}>
                {t('user.removeItem')}
              </a>
              <a
                href={`${blessing.base_url}/skinlib/show/${item.tid}`}
                className="dropdown-item"
                target="_blank"
              >
                {t('user.viewInSkinlib')}
              </a>
              <a href="#" className="dropdown-item" onClick={setAsAvatar}>
                {t('user.setAsAvatar')}
              </a>
            </div>
          </span>
        </div>
      </div>
    </div>
  )
}

export default ClosetItem
