// resources/assets/src/views/admin/Translations.vue
<template>
  <div>
    <vue-good-table
      :rows="lines"
      :columns="columns"
      :search-options="tableOptions.search"
      :pagination-options="tableOptions.pagination"
      style-class="vgt-table striped"
    >
      <template #table-row="props">
        <span v-if="props.column.field === 'operations'">
          <button class="btn btn-default" @click="modify(props.row)">
            {{ $t('admin.i18n.modify') }}
          </button>
          <button class="btn btn-danger" @click="remove(props.row)">
            {{ $t('admin.i18n.delete') }}
          </button>
        </span>
        <span v-else-if="props.column.field === 'text'">
          <span v-if="props.row.text" v-text="props.formattedRow[props.column.field]" />
          <i v-else>{{ $t('admin.i18n.empty') }}</i>
        </span>
        <span v-else v-text="props.formattedRow[props.column.field]" />
      </template>
    </vue-good-table>
  </div>
</template>

<script>
import { VueGoodTable } from 'vue-good-table'
import 'vue-good-table/dist/vue-good-table.min.css'
import tableOptions from '../../components/mixins/tableOptions'
import emitMounted from '../../components/mixins/emitMounted'
import { showModal, toast } from '../../scripts/notify'

export default {
  name: 'Translations',
  components: {
    VueGoodTable,
  },
  mixins: [
    emitMounted,
    tableOptions,
  ],
  data() {
    return {
      lines: [],
      columns: [
        { field: 'group', label: this.$t('admin.i18n.group') },
        { field: 'key', label: this.$t('admin.i18n.key') },
        { field: 'text', label: this.$t('admin.i18n.text') },
        {
          field: 'operations',
          label: this.$t('admin.operationsTitle'),
          sortable: false,
          globalSearchDisabled: true,
        },
      ],
    }
  },
  beforeMount() {
    this.fetchData()
  },
  methods: {
    async fetchData() {
      this.lines = await this.$http.get('/admin/i18n/list')
    },
    async modify(line) {
      let text = null
      try {
        ({ value: text } = await showModal({
          mode: 'prompt',
          text: this.$t('admin.i18n.updating'),
          input: line.text,
        }))
      } catch {
        return
      }

      const { code, message } = await this.$http.put(
        '/admin/i18n',
        { id: line.id, text },
      )
      if (code === 0) {
        line.text = text
        toast.success(message)
      } else {
        toast.error(message)
      }
    },
    async remove({ id, originalIndex }) {
      try {
        await showModal({
          text: this.$t('admin.i18n.confirmDelete'),
          okButtonType: 'danger',
        })
      } catch {
        return
      }

      const { message } = await this.$http.del('/admin/i18n', { id })
      this.$delete(this.lines, originalIndex)
      toast.success(message)
    },
  },
}
</script>

// resources/assets/src/views/admin/Translations/index.tsx
import type {Paginator} from '@/scripts/types';
import type {Line} from './types';
import Loading from '@/components/Loading';
import Pagination from '@/components/Pagination';
import {t} from '@/scripts/i18n';
import * as fetch from '@/scripts/net';
import {showModal, toast} from '@/scripts/notify';
import React, {useEffect, useState} from 'react';
import {useImmer} from 'use-immer';
import Row from './Row';

function Translations() {
	const [lines, setLines] = useImmer<Line[]>([]);
	const [isLoading, setIsLoading] = useState(true);
	const [page, setPage] = useState(1);
	const [totalPages, setTotalPages] = useState(1);

	useEffect(() => {
		const getLines = async () => {
			setIsLoading(true);
			const result = await fetch.get<Paginator<Line>>('/admin/i18n/list', {
				page: page.toString(),
			});
			setLines(() => result.data);
			setTotalPages(result.last_page);
			setIsLoading(false);
		};

		getLines();
	}, [page]);

	const handleEdit = async (line: Line, index: number) => {
		let text: string;
		try {
			const {value} = await showModal({
				mode: 'prompt',
				text: t('admin.i18n.updating'),
				input: line.text[blessing.locale],
			});
			text = value;
		} catch {
			return;
		}

		const {code, message} = await fetch.put<fetch.ResponseBody>(
			`/admin/i18n/${line.id}`,
			{text},
		);
		if (code === 0) {
			toast.success(message);
			setLines(lines => {
				lines[index].text[blessing.locale] = text;
			});
		} else {
			toast.error(message);
		}
	};

	const handleRemove = async (line: Line) => {
		try {
			await showModal({
				text: t('admin.i18n.confirmDelete'),
				okButtonType: 'danger',
			});
		} catch {
			return;
		}

		const {message} = await fetch.del(`/admin/i18n/${line.id}`);
		toast.success(String(message));
		const {id} = line;
		setLines(lines => lines.filter(line => line.id !== id));
	};

	return (
		<>
			<div className='card-body p-0'>
				<table className='table table-striped'>
					<thead>
						<tr>
							<th>{t('admin.i18n.group')}</th>
							<th>{t('admin.i18n.key')}</th>
							<th>{t('admin.i18n.text')}</th>
							<th>{t('admin.operationsTitle')}</th>
						</tr>
					</thead>
					<tbody>
						{isLoading
							? (
								<tr>
									<td className='text-center' colSpan={4}>
										<Loading/>
									</td>
								</tr>
							)
							: lines.length === 0
								? (
									<tr>
										<td className='text-center' colSpan={4}>
											{t('general.noResult')}
										</td>
									</tr>
								)
								: lines.map((line, i) => (
									<Row
										key={line.id}
										line={line}
										onEdit={async line => handleEdit(line, i)}
										onRemove={handleRemove}
									/>
								))}
					</tbody>
				</table>
			</div>
			<div className='card-footer d-flex flex-row-reverse'>
				<Pagination page={page} totalPages={totalPages} onChange={setPage}/>
			</div>
		</>
	);
}

export default Translations;
