// resources/assets/src/views/user/Closet/index.tsx
import React, { useState, useEffect } from 'react'
import { hot } from 'react-hot-loader/root'
import debounce from 'lodash.debounce'
import { t } from '@/scripts/i18n'
import * as fetch from '@/scripts/net'
import { showModal, toast } from '@/scripts/notify'
import { ClosetItem as Item, Texture } from '@/scripts/types'
import Loading from '@/components/Loading'
import Pagination from '@/components/Pagination'
import ClosetItem from './ClosetItem'
import Previewer from './Previewer'
import ModalApply from './ModalApply'

type Category = 'skin' | 'cape'

const updater = debounce(
  <T extends unknown>(
    value: React.SetStateAction<T>,
    setter: React.Dispatch<React.SetStateAction<T>>,
  ) => setter(value),
  350,
)

const Closet: React.FC = () => {
  const [isLoading, setIsLoading] = useState(false)
  const [category, setCategory] = useState<Category>('skin')
  const [search, setSearch] = useState('')
  const [query, setQuery] = useState('')
  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)
  const [items, setItems] = useState<Item[]>([])
  const [skin, setSkin] = useState<Texture | null>(null)
  const [cape, setCape] = useState<Texture | null>(null)
  const [showModalApply, setShowModalApply] = useState(false)

  useEffect(() => {
    const getItems = async () => {
      setIsLoading(true)
      const {
        data: { items, category: c, total_pages: totalPages },
      } = await fetch.get<
        fetch.ResponseBody<{
          items: Item[]
          category: Category
          total_pages: number
        }>
      >('/user/closet/list', {
        category,
        q: query,
        page,
      })

      setItems(items)
      setCategory(c)
      setTotalPages(totalPages)
      setIsLoading(false)
    }
    getItems()
  }, [category, query, page])

  const switchCategory = () => {
    setCategory(category => (category === 'skin' ? 'cape' : 'skin'))
  }

  const handleSearch = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value
    setSearch(value)
    updater(value, setQuery)
  }

  const handlePageChange = (page: number) => setPage(page)

  const isSelected = (item: Item): boolean => {
    if (category === 'skin') {
      return item.tid === skin?.tid
    } else {
      return item.tid === cape?.tid
    }
  }

  const handleSelect = (item: Item) => {
    if (item.type === 'cape') {
      setCape(item)
    } else {
      setSkin(item)
    }
  }

  const resetSelected = () => {
    setSkin(null)
    setCape(null)
  }

  const renameItem = async (item: Item, index: number) => {
    let name: string
    try {
      const { value } = await showModal({
        mode: 'prompt',
        text: t('user.renameClosetItem'),
        input: item.pivot.item_name,
        validator: (value: string) => {
          if (!value) {
            return t('skinlib.emptyNewTextureName')
          }
        },
      })
      name = value
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      `/user/closet/rename/${item.tid}`,
      { name },
    )
    if (code === 0) {
      toast.success(message)
      setItems(items => {
        items[index] = { ...item, pivot: { ...item.pivot, item_name: name } }
        return items.slice()
      })
    } else {
      toast.error(message)
    }
  }

  const removeItem = async (item: Item) => {
    try {
      await showModal({
        text: t('user.removeFromClosetNotice'),
        okButtonType: 'danger',
      })
    } catch {
      return
    }

    const { code, message } = await fetch.post<fetch.ResponseBody>(
      `/user/closet/remove/${item.tid}`,
    )
    if (code === 0) {
      toast.success(message)
      const { tid } = item
      setItems(items => items.filter(item => item.tid !== tid))
    } else {
      toast.error(message)
    }
  }

  const applyToPlayer = () => {
    if (!skin && !cape) {
      toast.info(t('user.emptySelectedTexture'))
      return
    }
    setShowModalApply(true)
  }

  return (
    <>
      <div className="card card-primary card-tabs">
        <div className="card-header p-0 pt-1 pl-1">
          <div className="d-flex justify-content-between">
            <ul className="nav nav-tabs" role="tablist">
              <li className="nav-item">
                <a
                  href="#"
                  className={`nav-link ${category === 'skin' ? 'active' : ''}`}
                  data-toggle="pill"
                  role="tab"
                  onClick={switchCategory}
                >
                  {t('general.skin')}
                </a>
              </li>
              <li className="nav-item">
                <a
                  href="#"
                  className={`nav-link ${category === 'cape' ? 'active' : ''}`}
                  data-toggle="pill"
                  role="tab"
                  onClick={switchCategory}
                >
                  {t('general.cape')}
                </a>
              </li>
              <li className="nav-item d-none d-md-block">
                <a
                  href={`${blessing.base_url}/skinlib/upload`}
                  className="nav-link"
                >
                  {t('user.closet.upload')}
                </a>
              </li>
            </ul>
            <div className="mr-3 my-2 my-lg-0">
              <input
                type="search"
                value={search}
                className="form-control mr-sm-2"
                aria-label="Search"
                placeholder={t('user.typeToSearch')}
                onChange={handleSearch}
              />
            </div>
          </div>
        </div>
        <div className="card-body">
          {isLoading ? (
            <Loading />
          ) : items.length === 0 ? (
            <div className="text-center p-3">
              {search ? (
                t('general.noResult')
              ) : (
                <span
                  dangerouslySetInnerHTML={{
                    __html: t('user.emptyClosetMsg', {
                      url: `${blessing.base_url}/skinlib?filter=${category}`,
                    }),
                  }}
                ></span>
              )}
            </div>
          ) : (
            <div className="d-flex flex-wrap">
              {items.map((item, i) => (
                <ClosetItem
                  key={item.tid}
                  item={item}
                  selected={isSelected(item)}
                  onClick={handleSelect}
                  onRename={() => renameItem(item, i)}
                  onRemove={() => removeItem(item)}
                />
              ))}
            </div>
          )}
        </div>
        <div className="card-footer">
          <div className="float-right">
            <Pagination
              page={page}
              totalPages={totalPages}
              onChange={handlePageChange}
            />
          </div>
        </div>
      </div>
      <Previewer
        skin={skin?.hash}
        cape={cape?.hash}
        isAlex={skin?.type === 'alex'}
      >
        <div className="d-flex justify-content-between">
          <button className="btn btn-primary" onClick={applyToPlayer}>
            {t('user.useAs')}
          </button>
          <button className="btn btn-default" onClick={resetSelected}>
            {t('user.resetSelected')}
          </button>
        </div>
      </Previewer>
      <ModalApply
        show={showModalApply}
        canAdd
        skin={skin?.tid}
        cape={cape?.tid}
        onClose={() => setShowModalApply(false)}
      />
    </>
  )
}

export default hot(Closet)

// resources/assets/src/views/user/Closet.vue
<template>
  <div class="container-fluid">
    <email-verification />
    <div class="row">
      <div class="col-md-8">
        <div class="card card-primary card-tabs">
          <div class="card-header p-0 pt-1 pl-1">
            <div class="d-flex justify-content-between">
              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a
                    class="nav-link"
                    :class="{ active: category === 'skin' }"
                    href="#"
                    data-toggle="pill"
                    role="tab"
                    @click="switchCategory"
                  >
                    {{ $t('general.skin') }}
                  </a>
                </li>
                <li class="nav-item">
                  <a
                    class="nav-link"
                    :class="{ active: category === 'cape' }"
                    href="#"
                    @click="switchCategory"
                  >
                    {{ $t('general.cape') }}
                  </a>
                </li>
                <li class="nav-item d-none d-md-block">
                  <a
                    v-t="'user.closet.upload'"
                    :href="`${baseUrl}/skinlib/upload`"
                    class="nav-link"
                  />
                </li>
              </ul>
              <div class="mr-3 my-2 my-lg-0">
                <input
                  v-model="query"
                  class="form-control mr-sm-2"
                  type="search"
                  aria-label="Search"
                  :placeholder="$t('user.typeToSearch')"
                  @input="search"
                >
              </div>
            </div>
          </div>
          <div class="card-body">
            <div
              v-if="category === 'skin'"
              id="skin-category"
              :class="{ active: category === 'skin' }"
            >
              <div v-if="skinItems.length === 0" class="text-center p-3">
                <div v-if="query !== ''" v-t="'general.noResult'" />
                <!-- eslint-disable-next-line vue/no-v-html -->
                <div v-else v-html="$t('user.emptyClosetMsg', { url: linkToSkin })" />
              </div>
              <div v-else class="d-flex flex-wrap">
                <closet-item
                  v-for="(item, index) in skinItems"
                  :key="item.tid"
                  :tid="item.tid"
                  :name="item.name"
                  :type="item.type"
                  :selected="selectedSkin === item.tid"
                  @select="selectTexture(item.tid)"
                  @item-removed="removeSkinItem(index)"
                />
              </div>
            </div>
            <div
              v-else
              id="cape-category"
              :class="{ active: category === 'cape' }"
            >
              <div v-if="capeItems.length === 0" class="text-center p-3">
                <div v-if="query !== ''" v-t="'general.noResult'" />
                <!-- eslint-disable-next-line vue/no-v-html -->
                <div v-else v-html="$t('user.emptyClosetMsg', { url: linkToCape })" />
              </div>
              <div v-else>
                <closet-item
                  v-for="(item, index) in capeItems"
                  :key="item.tid"
                  :tid="item.tid"
                  :name="item.name"
                  :type="item.type"
                  :selected="selectedCape === item.tid"
                  @select="selectTexture(item.tid)"
                  @item-removed="removeCapeItem(index)"
                />
              </div>
            </div>
          </div>
          <div class="card-footer">
            <paginate
              v-if="category === 'skin'"
              v-model="skinCurrentPage"
              :page-count="skinTotalPages"
              class="float-right"
              container-class="pagination pagination-sm no-margin"
              page-class="page-item"
              page-link-class="page-link"
              prev-class="page-item"
              prev-link-class="page-link"
              next-class="page-item"
              next-link-class="page-link"
              first-button-text="«"
              prev-text="‹"
              next-text="›"
              last-button-text="»"
              :click-handler="pageChanged"
              :first-last-button="true"
            />
            <paginate
              v-else
              v-model="capeCurrentPages"
              :page-count="capeTotalPages"
              class="float-right"
              container-class="pagination pagination-sm no-margin"
              page-class="page-item"
              page-link-class="page-link"
              prev-class="page-item"
              prev-link-class="page-link"
              next-class="page-item"
              next-link-class="page-link"
              first-button-text="«"
              prev-text="‹"
              next-text="›"
              last-button-text="»"
              :click-handler="pageChanged"
              :first-last-button="true"
            />
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <previewer
          closet-mode
          :skin="skinUrl"
          :cape="capeUrl"
          :model="model"
        >
          <template #footer>
            <div class="d-flex justify-content-between">
              <button
                class="btn btn-primary"
                data-toggle="modal"
                data-target="#modal-use-as"
                @click="fetchPlayersList"
              >
                {{ $t('user.useAs') }}
              </button>
              <button class="btn btn-default" data-test="resetSelected" @click="resetSelected">
                {{ $t('user.resetSelected') }}
              </button>
            </div>
          </template>
        </previewer>
      </div>
    </div>
    <apply-to-player-dialog ref="useAs" :skin="selectedSkin" :cape="selectedCape" />
    <add-player-dialog @add="fetchPlayersList" />
  </div>
</template>

<script>
import Paginate from 'vuejs-paginate'
import { debounce, queryString } from '../../scripts/utils'
import ClosetItem from '../../components/ClosetItem.vue'
import EmailVerification from '../../components/EmailVerification.vue'
import AddPlayerDialog from '../../components/AddPlayerDialog.vue'
import ApplyToPlayerDialog from '../../components/ApplyToPlayerDialog.vue'
import emitMounted from '../../components/mixins/emitMounted'

export default {
  name: 'Closet',
  components: {
    Paginate,
    ClosetItem,
    Previewer: () => import('../../components/Previewer.vue'),
    EmailVerification,
    AddPlayerDialog,
    ApplyToPlayerDialog,
  },
  mixins: [
    emitMounted,
  ],
  props: {
    baseUrl: {
      type: String,
      default: blessing.base_url,
    },
  },
  data: () => ({
    category: 'skin',
    query: '',
    skinItems: [],
    skinCurrentPage: 1,
    skinTotalPages: 1,
    capeItems: [],
    capeCurrentPages: 1,
    capeTotalPages: 1,
    selectedSkin: 0,
    skinUrl: '',
    model: 'steve',
    selectedCape: 0,
    capeUrl: '',
    linkToSkin: `${blessing.base_url}/skinlib?filter=skin`,
    linkToCape: `${blessing.base_url}/skinlib?filter=cape`,
  }),
  created() {
    this.search = debounce(this.loadCloset, 350)
  },
  beforeMount() {
    this.loadCloset()
  },
  mounted() {
    const tid = +queryString('tid', 0)
    if (tid) {
      this.selectTexture(tid)
      this.fetchPlayersList()
      $('#modal-use-as').modal()
    }
  },
  methods: {
    /* istanbul ignore next */
    search() {}, // eslint-disable-line no-empty-function
    async loadCloset(page = 1) {
      const {
        data: {
          items, category, total_pages: totalPages,
        },
      } = await this.$http.get(
        '/user/closet-data',
        {
          category: this.category,
          q: this.query,
          page,
        },
      )
      this[`${category}TotalPages`] = totalPages
      this[`${category}Items`] = items
      this[`${category}CurrentPages`] = page
    },
    removeSkinItem(index) {
      this.$delete(this.skinItems, index)
    },
    removeCapeItem(index) {
      this.$delete(this.capeItems, index)
    },
    switchCategory() {
      this.category = this.category === 'skin' ? 'cape' : 'skin'
      this.loadCloset(this[`${this.category}CurrentPages`])
    },
    pageChanged(page) {
      this.loadCloset(page)
    },
    async selectTexture(tid) {
      const { data: { type, hash } } = await this.$http.get(`/skinlib/info/${tid}`)
      if (type === 'cape') {
        this.capeUrl = `/textures/${hash}`
        this.selectedCape = tid
      } else {
        this.skinUrl = `/textures/${hash}`
        this.selectedSkin = tid
        this.model = type
      }
    },
    resetSelected() {
      this.selectedSkin = 0
      this.selectedCape = 0
      this.skinUrl = ''
      this.capeUrl = ''
    },
    fetchPlayersList() {
      this.$refs.useAs.fetchList()
    },
  },
}
</script>
